opera.isReady(function() {
  
var localisedStrings = {
// Afrikaans (Afrikaans)
"af": {
PREFERENCES:				"Voorkeure...",
DOWNLOAD_VIDEO:				"Aflaai video",
DOWNLOAD_EMPTY:				"(leeg)",
DOWNLOAD_EMPTY_TIP:			"Data vir aflaai nie gevind",
DOWNLOAD_UNKNOWN_TIP:		"onbekend video-formaat",
STEP_FRAME_FORWARD:			"Stap een raam vorentoe",
SEEK_FORWARD:				"Soek vorentoe",
SEEK_BACK:					"Soek terug",
POPOUT_PLAYER:				"Pop uit video-speler",
LOOP_DISABLE:				"Disable lus",
LOOP_ENABLE:				"Aktiveer lus",
LOOP_SECTION_DISABLE:		"Artikel lus afskakel",
LOOP_SECTION_ENABLE:		"Skakel die artikel lus",
LOOP_MARK_START:			"Mark artikel begin",
LOOP_MARK_END:				"Mark afdeling einde",
PREVIEW_START:				"Klik op video voorskou om te begin.",
PREVIEW_END:				"Klik op video voorskou aan die einde.",
LYRICS_BUTTON_HIDE:			"Steek lyrics",
LYRICS_BUTTON_SHOW:			"Wys lyrics",
LYRICS_BUTTON_LOAD:			"Load",
LYRICS_BUTTON_TRY:			"Probeer handmatig...",
LYRICS_LYRICS:				"Lyrics",
LYRICS_LYRICS_FOR:			"Lyrics vir: %song",
LYRICS_TITLE_INFO:			"Voeg kunstenaar en titel van die liedjie om te soek na.",
LYRICS_TITLE_INFO_EX:		"Skei deur koppelteken (soos so: Kunstenaar - Titel).",
LYRICS_SEARCH_START:		"Op soek na “%song”...",
LYRICS_SEARCH_NO_RESULT:	"Geen resultate vir “%song”.",
LYRICS_SEARCH_FOUND:		"Lyrics gevind. Loading...",
LYRICS_SEARCH_NOT_FOUND:	"Lyrics is nie gevind nie en nie meer kombinasies te probeer.",
LYRICS_PARSE_SEARCH:		"Parsing soek...",
LYRICS_PARSE_LYRICS:		"Parsing lyrics data...",
LYRICS_PARSE_SUCCESS:		"Lyrics suksesvol geparseerd.",
LYRICS_PARSE_ERROR:			"Lyrics is gevind, maar kan nie verwerk word nie. Jammer.",
LYRICS_TITLE_INVALID:		"Video titel nie ooreenstem met “kunstenaar - titel” patroon!",
RATING_LIKE:				"%pcent% laaiks",
RATING_NO_DATA:				"Video gradering nie beskikbaar nie."
},
// አማርኛ (Amharic)
// "am": {
// },
// العربية (Arabic)
"ar": {
PREFERENCES:				"تفضيلات...",
DOWNLOAD_VIDEO:				"تحميل الفيديو",
DOWNLOAD_EMPTY:				"(فارغ)",
DOWNLOAD_EMPTY_TIP:			"بيانات للتحميل لم يتم العثور على",
DOWNLOAD_UNKNOWN_TIP:		"غير معروف شكل فيديو",
STEP_FRAME_FORWARD:			"خطوة إلى الأمام في إطار واحد",
SEEK_FORWARD:				"تسعى إلى الأمام",
SEEK_BACK:					"تسعى مرة أخرى",
POPOUT_PLAYER:				"جحظ مشغل فيديو",
LOOP_DISABLE:				"تعطيل حلقة",
LOOP_ENABLE:				"تمكين حلقة",
LOOP_SECTION_DISABLE:		"تعطيل قسم حلقة",
LOOP_SECTION_ENABLE:		"تمكين حلقة القسم",
LOOP_MARK_START:			"مارك قسم بدء",
LOOP_MARK_END:				"علامة نهاية المقطع",
PREVIEW_START:				"انقر لبدء تشغيل معاينة الفيديو.",
PREVIEW_END:				"انقر لنهاية المعاينة الفيديو.",
LYRICS_BUTTON_HIDE:			"إخفاء كلمات",
LYRICS_BUTTON_SHOW:			"تظهر كلمات",
LYRICS_BUTTON_LOAD:			"تحميل",
LYRICS_BUTTON_TRY:			"محاولة يدويا...",
LYRICS_LYRICS:				"كلمات",
LYRICS_LYRICS_FOR:			"كلمات ل: %song",
LYRICS_TITLE_INFO:			"إدراج الفنان وعنوان الأغنية للبحث عن.",
LYRICS_TITLE_INFO_EX:		"منفصلة اصلة (مثل ذلك : الفنان - العنوان).",
LYRICS_SEARCH_START:		"البحث عن “%song”...",
LYRICS_SEARCH_NO_RESULT:	"لا نتائج ل “%song”.",
LYRICS_SEARCH_FOUND:		"العثور على كلمات. تحميل...",
LYRICS_SEARCH_NOT_FOUND:	"لم يتم العثور على كلمات وليس أكثر من محاولة لتركيبات.",
LYRICS_PARSE_SEARCH:		"توزيع نتائج البحث...",
LYRICS_PARSE_LYRICS:		"تحليل البيانات كلمات...",
LYRICS_PARSE_SUCCESS:		"كلمات تحليل بنجاح.",
LYRICS_PARSE_ERROR:			"تم العثور على كلمات ولكن لا يمكن أن يكون تحليل. عذرا.",
LYRICS_TITLE_INVALID:		"عنوان المقطع لا يطابق “الفنان -- العنوان” نمط!",
RATING_LIKE:				"أثار الفيديو إعجاب %pcent% من الأشخاص",
RATING_NO_DATA:				"غير متوفر التصنيف."
},
// Български (Bulgarian)
//	Thanks to:
//		Любомир <extrawordinary@hotmai.com>
"bg": {
PREFERENCES:				"Предпочитания...",
DOWNLOAD_VIDEO:				"Сваляне на видео",
DOWNLOAD_EMPTY:				"(Няма възможност да се свали)",
DOWNLOAD_EMPTY_TIP:			"Данни за изтегляне не са намерени",
DOWNLOAD_UNKNOWN_TIP:		"Непознат видео формат",
STEP_FRAME_FORWARD:			"Премини един кадър напред",
SEEK_FORWARD:				"Превърти напред",
SEEK_BACK:					"Върни назад",
POPOUT_PLAYER:				"Покажи само видео", // new
LOOP_DISABLE:				"Изключи автоматичното повторение",
LOOP_ENABLE:				"Включи автоматичното повторение",
LOOP_SECTION_DISABLE:		"Изключи повторението на зададената част",
LOOP_SECTION_ENABLE:		"Включи повторението на зададената част",
LOOP_MARK_START:			"Маркирай начална точка на повторение",
LOOP_MARK_END:				"Маркирай крайна точка на повторение",
PREVIEW_START:				"Кликнете да започне предварителен преглед на видео.", // new
PREVIEW_END:				"Натиснете до края на предварителен преглед на видео.", // new
LYRICS_BUTTON_HIDE:			"Скрий текста",
LYRICS_BUTTON_SHOW:			"Покажи текста",
LYRICS_BUTTON_LOAD:			"Зареди",
LYRICS_BUTTON_TRY:			"Ръчно въвеждане на текст...",
LYRICS_LYRICS:				"Текст",
LYRICS_LYRICS_FOR:			"Текст за: %song",
LYRICS_TITLE_INFO:			"Въведи изпълнител и заглавие на търсената песен.",
LYRICS_TITLE_INFO_EX:		"Разделяне с тире (пример: Изпълнител – Заглавие).",
LYRICS_SEARCH_START:		"Търсене на „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Не е намерен резултат за „%song“.",
LYRICS_SEARCH_FOUND:		"Намерен текст. Зареждане... ",
LYRICS_SEARCH_NOT_FOUND:	"Не е намерен текст и няма повече приложими комбинации.",
LYRICS_PARSE_SEARCH:		"Анализира се резултата от търсенето...",
LYRICS_PARSE_LYRICS:		"Анализиране на текста...",
LYRICS_PARSE_SUCCESS:		"Текстът е успешно анализиран.",
LYRICS_PARSE_ERROR:			"Намерен е текст, но за съжаление не може да бъде анализиран.",
LYRICS_TITLE_INVALID:		"Заглавието на видеото не отговаря на указаните „Изпълнител – Заглавие“!",
RATING_LIKE:				"%pcent% харесвания", // new
RATING_NO_DATA:				"Рейтинг не е налична." // new
},
// Беларуская (Belarusian)
//	Thanks to:
//		Jahor Sivahryvaŭ <Jahor@mail.by>
"be": {
PREFERENCES:				"Налады...",
DOWNLOAD_VIDEO:				"Запампаваць відэа",
DOWNLOAD_EMPTY:				"(пуста)",
DOWNLOAD_EMPTY_TIP:			"Няма чаго запампоўваць",
DOWNLOAD_UNKNOWN_TIP:		"невядомы фармат відэа", // new
STEP_FRAME_FORWARD:			"Перасунуцца на кадр наперад",
SEEK_FORWARD:				"Шукаць наперад",
SEEK_BACK:					"Шукаць назад",
POPOUT_PLAYER:				"Паказаць толькі відэа", // new
LOOP_DISABLE:				"Адключыць паўтор",
LOOP_ENABLE:				"Уключыць паўтор",
LOOP_SECTION_DISABLE:		"Адключыць частковы паўтор",
LOOP_SECTION_ENABLE:		"Уключыць частковы паўтор",
LOOP_MARK_START:			"Пазначыць пачатак часткі",
LOOP_MARK_END:				"Пазначыць канец часткі",
PREVIEW_START:				"Націсніце, каб пачаць прагляд відэа.", // new
PREVIEW_END:				"Націсніце да канца папярэдняга прагляду відэа.", // new
LYRICS_BUTTON_HIDE:			"Схаваць тэкст песьні",
LYRICS_BUTTON_SHOW:			"Адлюстраваць тэкст песьні",
LYRICS_BUTTON_LOAD:			"Загрузка",
LYRICS_BUTTON_TRY:			"Спрабаваць самастойна...",
LYRICS_LYRICS:				"Тэкст песьні",
LYRICS_LYRICS_FOR:			"Тэкст для песьні: %song",
LYRICS_TITLE_INFO:			"Пазначце артыста ды назву песьні для пошуку.",
LYRICS_TITLE_INFO_EX:		"Падзяляць злучком (напрыклад: Артыст - Назва).",
LYRICS_SEARCH_START:		"Пошук «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Нічога падобнага да «%song» ня знойдзена.",
LYRICS_SEARCH_FOUND:		"Знойдзены тэкст песьні. Загрузка...",
LYRICS_SEARCH_NOT_FOUND:	"Тэкст песьні ня знойдзены й ніякіх варыянтаў пошуку больш няма.",
LYRICS_PARSE_SEARCH:		"Аналіз вынікаў пошуку...",
LYRICS_PARSE_LYRICS:		"Аналіз тэкста песьні...",
LYRICS_PARSE_SUCCESS:		"Тэкст песьні пасьпяхова прааналізаваны.",
LYRICS_PARSE_ERROR:			"Тэкст песьні знойдзены але яго не атрымалася прааналізаваць. Выбачайце.",
LYRICS_TITLE_INVALID:		"Назва відэафайлу не адпавядае шаблёну «Артыст - Назва»!",
RATING_LIKE:				"%pcent% як", // new
RATING_NO_DATA:				"Рэйтынг не даступныя." // new
},
// বাংলা (Bengali)
"bn": {
PREFERENCES:				"পছন্দ...",
DOWNLOAD_VIDEO:				"ভিডিও ডাউনলোড করুন",
DOWNLOAD_EMPTY:				"(ফাঁকা)",
DOWNLOAD_EMPTY_TIP:			"পাওয়া ডাউনলোডের জন্য ডেটা না",
DOWNLOAD_UNKNOWN_TIP:		"অজানা ভিডিও বিন্যাস",
STEP_FRAME_FORWARD:			"এক ফ্রেম আগ বাড়া",
SEEK_FORWARD:				"সামনের দিকে খোঁজ",
SEEK_BACK:					"ফিরে খোঁজ",
POPOUT_PLAYER:				"ভিডিও প্লেয়ার পপ আউট",
LOOP_DISABLE:				"পরিহারের উপায় নিষ্ক্রিয় করুন",
LOOP_ENABLE:				"লুপ সক্রিয় করুন",
LOOP_SECTION_DISABLE:		"অধ্যায় লুপ নিষ্ক্রিয় করুন",
LOOP_SECTION_ENABLE:		"অধ্যায় লুপ সক্রিয় করুন",
LOOP_MARK_START:			"মার্ক অধ্যায় শুরু",
LOOP_MARK_END:				"মার্ক অধ্যায় শেষ",
PREVIEW_START:				"ভিডিও প্রাকদর্শন করুন.",
PREVIEW_END:				"থেকে ভিডিওর পূর্বদৃশ্য শেষ ক্লিক করুন.",
LYRICS_BUTTON_HIDE:			"গানের লুকান",
LYRICS_BUTTON_SHOW:			"গানের দেখাও",
LYRICS_BUTTON_LOAD:			"লোড",
LYRICS_BUTTON_TRY:			"নিজে চেষ্টা করুন...",
LYRICS_LYRICS:				"গান",
LYRICS_LYRICS_FOR:			"জন্য গান: %song",
LYRICS_TITLE_INFO:			"শিল্পী এবং সঙ্গীত এর শিরোনামটি অনুসন্ধান ঢোকান.",
LYRICS_TITLE_INFO_EX:		"হাইফেন (মত তাই: শিরোনাম - শিল্পী) দ্বারা পৃথক.",
LYRICS_SEARCH_START:		"\"%song\" জন্য অনুসন্ধান করছি...",
LYRICS_SEARCH_NO_RESULT:	"\"%song\" জন্য কোন ফলাফল.",
LYRICS_SEARCH_FOUND:		"গান পাওয়া যায়. লোড হচ্ছে...",
LYRICS_SEARCH_NOT_FOUND:	"গান এবং কোনো আরো সমন্বয় করার চেষ্টা পাওয়া যায় না.",
LYRICS_PARSE_SEARCH:		"অনুসন্ধান ফলাফল পার্স...",
LYRICS_PARSE_LYRICS:		"গানের তথ্য পার্স...",
LYRICS_PARSE_SUCCESS:		"গান সাফল্যের বিশ্লেষণ.",
LYRICS_PARSE_ERROR:			"লিরিক কিন্তু পাওয়া বিশ্লেষণ করা যাবে না হয়. দুঃখিত.",
LYRICS_TITLE_INVALID:		"ভিডিও শিরোনাম \"শিল্পী - শিরোনাম\" না মেলে প্যাটার্ন!",
RATING_LIKE:				"%pcent% মত",
RATING_NO_DATA:				"উপলব্ধ নির্ধারণ না."
},
// Català (Catalan; Valencian)
"ca": {
PREFERENCES:				"Preferències...",
DOWNLOAD_VIDEO:				"Descarregar el vídeo",
DOWNLOAD_EMPTY:				"(buit)",
DOWNLOAD_EMPTY_TIP:			"Dades per a la descàrrega no es troba",
DOWNLOAD_UNKNOWN_TIP:		"format de vídeo desconegut",
STEP_FRAME_FORWARD:			"Pas de la imatge següent",
SEEK_FORWARD:				"Cercar cap endavant",
SEEK_BACK:					"Cercar cap enrere",
POPOUT_PLAYER:				"Mostra només vídeo",
LOOP_DISABLE:				"Llaç de desactivar",
LOOP_ENABLE:				"Permeten bucle",
LOOP_SECTION_DISABLE:		"Bucle secció desactivar",
LOOP_SECTION_ENABLE:		"Permetre que la secció del llaç",
LOOP_MARK_START:			"Marca d’inici de la secció",
LOOP_MARK_END:				"Marca de cap secció",
PREVIEW_START:				"Feu clic per començar a vista prèvia de vídeo.",
PREVIEW_END:				"Feu clic per finalitzar vista prèvia de vídeo.",
LYRICS_BUTTON_HIDE:			"Amaga lletres de cançons",
LYRICS_BUTTON_SHOW:			"Lletres de cançons mostren",
LYRICS_BUTTON_LOAD:			"De càrrega",
LYRICS_BUTTON_TRY:			"Tractar de forma manual...",
LYRICS_LYRICS:				"Lletres de cançons",
LYRICS_LYRICS_FOR:			"Lletres de cançons de: %song",
LYRICS_TITLE_INFO:			"Inseriu artista i el títol de la cançó que voleu cercar.",
LYRICS_TITLE_INFO_EX:		"Separats per un guió (d’aquesta manera: Artista - Títol).",
LYRICS_SEARCH_START:		"A la recerca de «%song»...",
LYRICS_SEARCH_NO_RESULT:	"No hi ha resultats per a «%song».",
LYRICS_SEARCH_FOUND:		"Lletres que es troben. Carregant...",
LYRICS_SEARCH_NOT_FOUND:	"Lletres no es troben ni més combinacions intentar.",
LYRICS_PARSE_SEARCH:		"Analitzar els resultats de cerca...",
LYRICS_PARSE_LYRICS:		"Lletres d’anàlisi de dades...",
LYRICS_PARSE_SUCCESS:		"Lletres d’analitzar correctament.",
LYRICS_PARSE_ERROR:			"Lletres es troben, però no es pot analitzar. Ho sentim.",
LYRICS_TITLE_INVALID:		"Títol del vídeo no coincideix amb «Artista - Títol» patró!",
RATING_LIKE:				"%pcent% «M’agrada»",
RATING_NO_DATA:				"Categoria no disponible."
},
// Čeština (Czech)
//	Thanks to:
//		watrill,
//		RomanK47
"cs": {
PREFERENCES:				"Nastavení...",
DOWNLOAD_VIDEO:				"Stáhnout",
DOWNLOAD_EMPTY:				"(prázdné)",
DOWNLOAD_EMPTY_TIP:			"Požadovaná data nebyla nalezena",
DOWNLOAD_UNKNOWN_TIP:		"neznámý formát videa", // new
STEP_FRAME_FORWARD:			"Krok o jeden snímek vpřed",
SEEK_FORWARD:				"Skok vpřed",
SEEK_BACK:					"Skok zpět",
POPOUT_PLAYER:				"Zobrazit pouze video", // new
LOOP_DISABLE:				"Zakázat smyčku",
LOOP_ENABLE:				"Povolit smyčku",
LOOP_SECTION_DISABLE:		"Zakázat smyčku výběru",
LOOP_SECTION_ENABLE:		"Povolit smyčku výběru",
LOOP_MARK_START:			"Začátek výběru",
LOOP_MARK_END:				"Konec výběru",
PREVIEW_START:				"Klepněte na tlačítko pro spuštění videa náhledu.", // new
PREVIEW_END:				"Klikněte do konce náhled videa.", // new
LYRICS_BUTTON_HIDE:			"Skrýt text písně",
LYRICS_BUTTON_SHOW:			"Zobrazit text písně",
LYRICS_BUTTON_LOAD:			"Načíst",
LYRICS_BUTTON_TRY:			"Zkusit najít ručně...",
LYRICS_LYRICS:				"Text písně",
LYRICS_LYRICS_FOR:			"Text písně: %song",
LYRICS_TITLE_INFO:			"Vložte jméno interpreta a písně, kterou chcete hledat.",
LYRICS_TITLE_INFO_EX:		"Oddělte pomlčkou (například: Interpret - Název písně).",
LYRICS_SEARCH_START:		"Vyhledávání „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Žádné výsledky pro „%song“.",
LYRICS_SEARCH_FOUND:		"Text písně nalezen. Načítání...",
LYRICS_SEARCH_NOT_FOUND:	"Byly vyzkoušeny všechny možné kombinace, ale text písně nebyl nalezen.",
LYRICS_PARSE_SEARCH:		"Zpracovávání výsledků hledání...",
LYRICS_PARSE_LYRICS:		"Zpracování textů...",
LYRICS_PARSE_SUCCESS:		"Text písně úspěšně zpracován.",
LYRICS_PARSE_ERROR:			"Text byl nalezen, ale není možné jej zpracovat. Omlouvám se.",
LYRICS_TITLE_INVALID:		"Název videa neodpovídá vzoru „Interpret - Název písně“!",
RATING_LIKE:				"Líbí se: %pcent%", // new
RATING_NO_DATA:				"Hodnocení není k dispozici." // new
},
// Dansk (Danish)
//	Thanks to:
//		Frederik Riboe Olsen
"da": {
PREFERENCES:				"Præferencer...",
DOWNLOAD_VIDEO:				"Hent video",
DOWNLOAD_EMPTY:				"(Tom)",
DOWNLOAD_EMPTY_TIP:			"Data til nedhentning ikke fundet",
DOWNLOAD_UNKNOWN_TIP:		"ukendt videoformat", // new
STEP_FRAME_FORWARD:			"Gå et billede frem",
SEEK_FORWARD:				"Spol frem",
SEEK_BACK:					"Spol tilbage",
POPOUT_PLAYER:				"Pop ud videoafspiller", // new
LOOP_DISABLE:				"Deaktiver gentagelse",
LOOP_ENABLE:				"Aktiver gentagelse",
LOOP_SECTION_DISABLE:		"Deaktiver sektionsgentagelse",
LOOP_SECTION_ENABLE:		"Aktiver sektionsgentagelse",
LOOP_MARK_START:			"Marker sektionens start",
LOOP_MARK_END:				"Marker sektionens slutning",
PREVIEW_START:				"Klik for at starte video preview.", // new
PREVIEW_END:				"Klik for at afslutte video preview.", // new
LYRICS_BUTTON_HIDE:			"Skjul tekster",
LYRICS_BUTTON_SHOW:			"Vis tekster",
LYRICS_BUTTON_LOAD:			"Indlæs",
LYRICS_BUTTON_TRY:			"Prøv manuelt...",
LYRICS_LYRICS:				"Tekster",
LYRICS_LYRICS_FOR:			"Tekster for: %song",
LYRICS_TITLE_INFO:			"Indsæt kunstner og titlen på sangen du vil søge efter.",
LYRICS_TITLE_INFO_EX:		"Adskilt med bindestreg (Sådan: Kunstner - Titel).",
LYRICS_SEARCH_START:		"Søger efter »%song«...",
LYRICS_SEARCH_NO_RESULT:	"Ingen resultater for »%song«.",
LYRICS_SEARCH_FOUND:		"Tekster fundet. Henter...",
LYRICS_SEARCH_NOT_FOUND:	"Teksterne blev ikke fundet og der er ikke flere kombinationer at prøve.",
LYRICS_PARSE_SEARCH:		"Tolker søgeresultater...",
LYRICS_PARSE_LYRICS:		"Tolker tekst data...",
LYRICS_PARSE_SUCCESS:		"Tekster successfuldt tolket.",
LYRICS_PARSE_ERROR:			"Teksterne er fundet, men kan ikke tolkes. Beklager.",
LYRICS_TITLE_INVALID:		"Videotitlen passer ikke til »Kunstner - Titel« formatet!",
RATING_LIKE:				"%pcent% synes godt om", // new
RATING_NO_DATA:				"Video bedømmelse ikke tilgængelig." // new
},
// Deutsch (German)
//	Thanks to:
//		Ralf Beckebans
//		Steve K. <velocity@bossmail.de>
//		Gedeon
//		Andreas Böhm
//		Carl Aron Carls <carlaron@carls.de>
//		Nicola Markus Pfister <nicola@besonet.ch>
"de": {
PREFERENCES:				"Einstellungen...",
DOWNLOAD_VIDEO:				"Video herunterladen",
DOWNLOAD_EMPTY:				"(leer)",
DOWNLOAD_EMPTY_TIP:			"Herunterzuladende Daten wurden nicht gefunden",
DOWNLOAD_UNKNOWN_TIP:		"unbekannten Video-Format", // new
STEP_FRAME_FORWARD:			"Einen Frame vorwärts",
SEEK_FORWARD:				"Vorspulen",
SEEK_BACK:					"Zurückspulen",
POPOUT_PLAYER:				"Video zeigen nur", // new
LOOP_DISABLE:				"Wiederholung ausschalten",
LOOP_ENABLE:				"Wiederholung einschalten",
LOOP_SECTION_DISABLE:		"Wiederholung eines Abschnitts ausschalten",
LOOP_SECTION_ENABLE:		"Wiederholung eines Abschnitts einschalten",
LOOP_MARK_START:			"Start eines Abschnitts markieren",
LOOP_MARK_END:				"Ende eines Abschnitts markieren",
PREVIEW_START:				"Hier klicken, um Video-Vorschau zu starten.", // new
PREVIEW_END:				"Hier klicken, um Video-Vorschau zu beenden.", // new
LYRICS_BUTTON_HIDE:			"Verstecke den Liedtext",
LYRICS_BUTTON_SHOW:			"Zeige den Liedtext an",
LYRICS_BUTTON_LOAD:			"Laden",
LYRICS_BUTTON_TRY:			"Manuell suchen...",
LYRICS_LYRICS:				"Liedtext",
LYRICS_LYRICS_FOR:			"Liedtext für: %song",
LYRICS_TITLE_INFO:			"Bitte Interpret und Titel im Suchfeld eingeben.",
LYRICS_TITLE_INFO_EX:		"Eingabe getrennt durch Bindestrich (Format: Interpret - Titel)",
LYRICS_SEARCH_START:		"Suche nach „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Keine Ergebnisse für „%song“.",
LYRICS_SEARCH_FOUND:		"Liedtext gefunden. Wird geladen...",
LYRICS_SEARCH_NOT_FOUND:	"Liedtext wurde auch in verschiedenen Kombinationen  nicht gefunden.",
LYRICS_PARSE_SEARCH:		"Analysiere Resultate...",
LYRICS_PARSE_LYRICS:		"Analysiere die Liedtext Daten...",
LYRICS_PARSE_SUCCESS:		"Liedtext wurde erfolgreich analysiert.",
LYRICS_PARSE_ERROR:			"Leider konnte der Liedtext nicht gefunden und analysiert werden.",
LYRICS_TITLE_INVALID:		"Der Suchtext wurde nicht im Format „Interpret - Titel“ eingegeben!",
RATING_LIKE:				"Gefällt %pcent%", // new
RATING_NO_DATA:				"Bewertung nicht verfügbar." // new
},
// Ελληνικά (Greek)
//	Thanks to:
//		Murat SO <so.murat@hotmail.com>
"el": {
PREFERENCES:				"Ρυθμίσεις...",
DOWNLOAD_VIDEO:				"Κατεβάστε το βίντεο",
DOWNLOAD_EMPTY:				"(κενό)",
DOWNLOAD_EMPTY_TIP:			"Δεν βρέθηκαν δεδομένα για κατέβασμα",
DOWNLOAD_UNKNOWN_TIP:		"άγνωστη μορφή βίντεο", // new
STEP_FRAME_FORWARD:			"Ένα πλαίσιο μπροστά",
SEEK_FORWARD:				"Μπροστά",
SEEK_BACK:					"Πίσω",
POPOUT_PLAYER:				"Προβολή βίντεο μόνο", // new
LOOP_DISABLE:				"Απενεργοποίηση επανάληψης",
LOOP_ENABLE:				"Ενεργοποίηση επανάληψης",
LOOP_SECTION_DISABLE:		"Απενεργοποίηση επανάληψης τμήματος",
LOOP_SECTION_ENABLE:		"Ενεργοποίηση επανάληψης τμήματος",
LOOP_MARK_START:			"Σήμανση αρχής τμήματος",
LOOP_MARK_END:				"Σήμανση τέλους τμήματος",
PREVIEW_START:				"Κάντε κλικ στο κουμπί για να ξεκινήσει προεπισκόπηση βίντεο.", // new
PREVIEW_END:				"Κάντε κλικ στο τέλος προεπισκόπηση βίντεο.", // new
LYRICS_BUTTON_HIDE:			"Κρύψε τους στίχους",
LYRICS_BUTTON_SHOW:			"Εμφάνισε τους στίχους",
LYRICS_BUTTON_LOAD:			"Αναζήτηση",
LYRICS_BUTTON_TRY:			"Δοκιμάστε χειροκίνητα...",
LYRICS_LYRICS:				"Στίχοι",
LYRICS_LYRICS_FOR:			"Στίχοι για: %song",
LYRICS_TITLE_INFO:			"Εισαγωγή καλλιτέχνη και τίτλου τραγουδιού για αναζήτηση.",
LYRICS_TITLE_INFO_EX:		"Διαχωρίστε με παύλα (π.χ. Καλλιτέχνης - Τίτλος).",
LYRICS_SEARCH_START:		"Αναζήτηση για «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Δεν βρέθηκαν αποτελέσματα για «%song».",
LYRICS_SEARCH_FOUND:		"Οι στίχοι βρέθηκαν. Φορτώνονται...",
LYRICS_SEARCH_NOT_FOUND:	"Δεν βρέθηκαν στίχοι και δεν υπάρχουν άλλοι συνδυασμοί για αναζήτηση.",
LYRICS_PARSE_SEARCH:		"Ανάλυση αποτελεσμάτων αναζήτησης...",
LYRICS_PARSE_LYRICS:		"Ανάλυση δεδομένων στίχων...",
LYRICS_PARSE_SUCCESS:		"Ανάλυση των στίχων ολοκληρώθηκε επιτυχώς.",
LYRICS_PARSE_ERROR:			"Οι στίχοι βρέθηκαν αλλά δεν μπορούν να αναλυθούν. Συγγνώμη.",
LYRICS_TITLE_INVALID:		"Ο τίτλος του βίντεο δεν αντιστοιχεί στο σχήμα «Καλλιτέχνης - Τίτλος»!",
RATING_LIKE:				"%pcent% θετικές", // new
RATING_NO_DATA:				"Αξιολόγηση δεν είναι διαθέσιμη." // new
},
// English (English)
//	Thanks to: me :), Darko Pantić
"en": {
PREFERENCES:				"Preferences...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(empty)",
DOWNLOAD_EMPTY_TIP:			"Data for download not found",
DOWNLOAD_UNKNOWN_TIP:		"unknown video format",
STEP_FRAME_FORWARD:			"Step one frame forward",
SEEK_FORWARD:				"Seek forward",
SEEK_BACK:					"Seek back",
POPOUT_PLAYER:				"Pop out video player",
LOOP_DISABLE:				"Disable loop",
LOOP_ENABLE:				"Enable loop",
LOOP_SECTION_DISABLE:		"Disable section loop",
LOOP_SECTION_ENABLE:		"Enable section loop",
LOOP_MARK_START:			"Mark section start",
LOOP_MARK_END:				"Mark section end",
PREVIEW_START:				"Click to start video preview.",
PREVIEW_END:				"Click to end video preview.",
LYRICS_BUTTON_HIDE:			"Hide lyrics",
LYRICS_BUTTON_SHOW:			"Show lyrics",
LYRICS_BUTTON_LOAD:			"Load",
LYRICS_BUTTON_TRY:			"Try manually...",
LYRICS_LYRICS:				"Lyrics",
LYRICS_LYRICS_FOR:			"Lyrics for: %song",
LYRICS_TITLE_INFO:			"Insert artist and title of song to search for.",
LYRICS_TITLE_INFO_EX:		"Separate with hyphen (like so: Artist - Title).",
LYRICS_SEARCH_START:		"Searching for “%song”...",
LYRICS_SEARCH_NO_RESULT:	"No results for “%song”.",
LYRICS_SEARCH_FOUND:		"Lyrics found. Loading...",
LYRICS_SEARCH_NOT_FOUND:	"Lyrics are not found and no more combinations to try.",
LYRICS_PARSE_SEARCH:		"Parsing search results...",
LYRICS_PARSE_LYRICS:		"Parsing lyrics data...",
LYRICS_PARSE_SUCCESS:		"Lyrics successfully parsed.",
LYRICS_PARSE_ERROR:			"Lyrics are found but cannot be parsed. Sorry.",
LYRICS_TITLE_INVALID:		"Video title doesn’t match “Artist - Title” pattern!",
RATING_LIKE:				"%pcent% like",
RATING_NO_DATA:				"Rating not available."
},
// Español (Spanish)
//	Thanks to:
//		Santiago Puerto <santiago.puerto@gmail.com>
//		LuKaZ PaiN <lukaznet@gmail.com>
//		José Manuel Navarro Vargas <elkotox3@live.cl>
"es": {
PREFERENCES:				"Opciones...",
DOWNLOAD_VIDEO:				"Descargar vídeo",
DOWNLOAD_EMPTY:				"(Descargar vacía)",
DOWNLOAD_EMPTY_TIP:			"No se encuentran datos para la descarga",
DOWNLOAD_UNKNOWN_TIP:		"formato de vídeo desconocido", // new
STEP_FRAME_FORWARD:			"Saltar un frame adelante",
SEEK_FORWARD:				"Buscar adelante",
SEEK_BACK:					"Buscar atras",
POPOUT_PLAYER:				"Videos mostrando sólo", // new
LOOP_DISABLE:				"Desactivar bucle",
LOOP_ENABLE:				"Activar bucle",
LOOP_SECTION_DISABLE:		"Desactivar sección de bucle",
LOOP_SECTION_ENABLE:		"Activar sección de bucle",
LOOP_MARK_START:			"Marcar inicio de sección",
LOOP_MARK_END:				"Marcar fin de sección",
PREVIEW_START:				"Haga clic para empezar a vista previa de vídeo.", // new
PREVIEW_END:				"Haga clic para finalizar vista previa de vídeo.", // new
LYRICS_BUTTON_HIDE:			"Ocultar letras de canciones",
LYRICS_BUTTON_SHOW:			"Mostrar letras de canciones",
LYRICS_BUTTON_LOAD:			"Cargar",
LYRICS_BUTTON_TRY:			"Intentar manualmente...",
LYRICS_LYRICS:				"Letras de canciones",
LYRICS_LYRICS_FOR:			"Letras para: %song",
LYRICS_TITLE_INFO:			"Inserte artista y título de la cancion a buscar.",
LYRICS_TITLE_INFO_EX:		"Separado por un guión (por ejempli: Artista - Título).",
LYRICS_SEARCH_START:		"Búscando «%song»...",
LYRICS_SEARCH_NO_RESULT:	"No hay resultados para «%song».",
LYRICS_SEARCH_FOUND:		"Letras encontradas. Cargando...",
LYRICS_SEARCH_NOT_FOUND:	"Letras no encontradas y no hay mas combinaciones para probar.",
LYRICS_PARSE_SEARCH:		"Procesando los resultados de la búsqueda...",
LYRICS_PARSE_LYRICS:		"Procesando datos de lyrics...",
LYRICS_PARSE_SUCCESS:		"Letras analizadas correctamente.",
LYRICS_PARSE_ERROR:			"Las letras se encuentran, pero no se pueden analizar. Lo siento.",
LYRICS_TITLE_INVALID:		"El título del vídeo no coincide «Artista - Título» patron!",
RATING_LIKE:				"Me gusta: %pcent%", // new
RATING_NO_DATA:				"Categoría no disponible." // new
},
// Eesti keel (Estonian)
//	Thanks to:
//		Alexander Assmann
"et": {
PREFERENCES:				"Eelistused...",
DOWNLOAD_VIDEO:				"Laadi video alla",
DOWNLOAD_EMPTY:				"(tühi)",
DOWNLOAD_EMPTY_TIP:			"Andmeid allalaadimiseks ei leitud",
DOWNLOAD_UNKNOWN_TIP:		"tundmatu videoformaadis", // new
STEP_FRAME_FORWARD:			"Üks kaader edasi",
SEEK_FORWARD:				"Keri edasi",
SEEK_BACK:					"Keri tagasi",
POPOUT_PLAYER:				"Tupsahtaa videopleier", // new
LOOP_DISABLE:				"Kordus välja",
LOOP_ENABLE:				"Kordus sisse",
LOOP_SECTION_DISABLE:		"Lõigu kordus välja",
LOOP_SECTION_ENABLE:		"Lõigu kordus sisse",
LOOP_MARK_START:			"Märgi lõigu algus",
LOOP_MARK_END:				"Märgi lõigu lõpp",
PREVIEW_START:				"Klõpsake alustamiseks video eelvaade.", // new
PREVIEW_END:				"Klikka end video eelvaade.", // new
LYRICS_BUTTON_HIDE:			"Peida laulusõnad",
LYRICS_BUTTON_SHOW:			"Näita laulusõnu",
LYRICS_BUTTON_LOAD:			"Lae",
LYRICS_BUTTON_TRY:			"Proovi käsitsi...",
LYRICS_LYRICS:				"Laulusõnad",
LYRICS_LYRICS_FOR:			"Laulusõnad: %song",
LYRICS_TITLE_INFO:			"Sisesta otsitava laulu esitaja ja pealkiri.",
LYRICS_TITLE_INFO_EX:		"Eralda sidekriipsuga (näiteks: Esitaja - Pealkiri).",
LYRICS_SEARCH_START:		"Otsimine „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Tulemused „%song“.",
LYRICS_SEARCH_FOUND:		"Laulusõnad leitud. Laadimine...",
LYRICS_SEARCH_NOT_FOUND:	"Laulusõnu ei leitud. Rohkem kombinatsioone proovida ei ole.",
LYRICS_PARSE_SEARCH:		"Otsingutulemuste sõelumine...",
LYRICS_PARSE_LYRICS:		"Laulusõnade andmete sõelumine...",
LYRICS_PARSE_SUCCESS:		"Laulusõnad edukalt sõelutud.",
LYRICS_PARSE_ERROR:			"Laulusõnad on leitud, aga neid ei ole võimalik sõeluda. Vabandust.",
LYRICS_TITLE_INVALID:		"Video pealkiri ei klapi „Esitaja - Pealkiri“ mustriga!",
RATING_LIKE:				"%pcent% kasutajale meeldis", // new
RATING_NO_DATA:				"Hinnang ei ole saadaval." // new
},
// Euskara (Basque)
"eu": {
PREFERENCES:				"Aukerak...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(hutsik)",
DOWNLOAD_EMPTY_TIP:			"Deskargatu datuak ez dira aurkitu",
DOWNLOAD_UNKNOWN_TIP:		"Bideoaren formatua ezezaguna",
STEP_FRAME_FORWARD:			"Step bat frame aurrera",
SEEK_FORWARD:				"Jo aurrera",
SEEK_BACK:					"Jo atzera",
POPOUT_PLAYER:				"Pop izarrekin video player",
LOOP_DISABLE:				"Desgaitu begizta",
LOOP_ENABLE:				"Gaitu begizta",
LOOP_SECTION_DISABLE:		"Desgaitu Atal begizta",
LOOP_SECTION_ENABLE:		"Gaitu Atal begizta",
LOOP_MARK_START:			"Mark Atal Irteeran",
LOOP_MARK_END:				"Mark Atal bukaera",
PREVIEW_START:				"Egin klik bideoa preview hasteko.",
PREVIEW_END:				"Egin klik bideoa preview amaiera emateko.",
LYRICS_BUTTON_HIDE:			"Ezkutatu lyrics",
LYRICS_BUTTON_SHOW:			"Erakutsi lyrics",
LYRICS_BUTTON_LOAD:			"Kargatu",
LYRICS_BUTTON_TRY:			"Saiatu eskuz...",
LYRICS_LYRICS:				"Lyrics",
LYRICS_LYRICS_FOR:			"Lyrics for %song",
LYRICS_TITLE_INFO:			"Txertatu artista eta abestiaren izenburua bilatzeko.",
LYRICS_TITLE_INFO_EX:		"Marratxo by bereizia (beraz: Artist - Izenburua).",
LYRICS_SEARCH_START:		"Bilatzea «%song»...",
LYRICS_SEARCH_NO_RESULT:	"No results for «%song».",
LYRICS_SEARCH_FOUND:		"Lyrics aurkitu. Kargatzen...",
LYRICS_SEARCH_NOT_FOUND:	"Lyrics ez da aurkitu dira eta gehiago konbinazioak ez saiatzeko.",
LYRICS_PARSE_SEARCH:		"Bilaketaren emaitzak Parsing...",
LYRICS_PARSE_LYRICS:		"Lyrics datuak Parsing...",
LYRICS_PARSE_SUCCESS:		"Lyrics arrakastaz analizatu.",
LYRICS_PARSE_ERROR:			"Lyrics dira, baina ezin da analizatu. Barkatu.",
LYRICS_TITLE_INVALID:		"Video title «Artist - Izenburua» ereduarekin ez dator bat!",
RATING_LIKE:				"%pcent% erabiltzaileri gustatu zaie",
RATING_NO_DATA:				"Puntuatu gabe dago."
},
// فارسی (Persian)
//	Thanks to:
//		Hessam Sameri
"fa": {
PREFERENCES:				"تنظيمات",
DOWNLOAD_VIDEO:				"دانلود ويدئو",
DOWNLOAD_EMPTY:				"(خالي)",
DOWNLOAD_EMPTY_TIP:			"اطلاعاتي براي دانلود پيدا نشد",
DOWNLOAD_UNKNOWN_TIP:		"فرمت های تصویری ناشناخته", // new
STEP_FRAME_FORWARD:			"يک فريم به جلو",
SEEK_FORWARD:				"جلو بردن",
SEEK_BACK:					"عقب بردن",
POPOUT_PLAYER:				"پاپ از پخش ویدئو", // new
LOOP_DISABLE:				"غيرفعال کردن حلقه",
LOOP_ENABLE:				"فعال کردن حلقه",
LOOP_SECTION_DISABLE:		"غيرفعال کردن حلقه براي قطعه",
LOOP_SECTION_ENABLE:		"غيرفعال کردن حلقه براي قطعه",
LOOP_MARK_START:			"شروع قطعه",
LOOP_MARK_END:				"پايان قطعه",
PREVIEW_START:				"بر روی پیش نمایش فیلم برای شروع کلیک کنید.", // new
PREVIEW_END:				"بر روی پیش نمایش فیلم برای پایان دادن به کلیک کنید.", // new
LYRICS_BUTTON_HIDE:			"مخفي کردن شعر",
LYRICS_BUTTON_SHOW:			"نمايش شعر",
LYRICS_BUTTON_LOAD:			"بارگذاري",
LYRICS_BUTTON_TRY:			"به صورت دستي امتحان کنيد",
LYRICS_LYRICS:				"شعر",
LYRICS_LYRICS_FOR:			"شعر براي: %song",
LYRICS_TITLE_INFO:			"نام خواننده و عنوان ترانه را براي جستجو وارد نماييد.",
LYRICS_TITLE_INFO_EX:		"با خط تيره جدا کنيد (مثل: خواننده - عنوان).",
LYRICS_SEARCH_START:		"جستجو براي “%song”...",
LYRICS_SEARCH_NO_RESULT:	"نتيجه اي يافت نشد براي “%song”.",
LYRICS_SEARCH_FOUND:		"شعر پيدا شد.درحال بارگذاري...",
LYRICS_SEARCH_NOT_FOUND:	"شعر يافت نشد و ترکيب ديگري براي جستجو کردن وجود ندارد",
LYRICS_PARSE_SEARCH:		"تجزيه نتايج جستجو...",
LYRICS_PARSE_LYRICS:		"تجزيه اطلاعات شعر...",
LYRICS_PARSE_SUCCESS:		"شعر به خوبي تجزيه شد.",
LYRICS_PARSE_ERROR:			"شعر پيدا شد اما قابل تجزيه شدن نيست،ببخشيد!",
LYRICS_TITLE_INVALID:		"عنوان ويدئو با الگوي “خواننده - عنوان” سازگاري ندارد!",
RATING_LIKE:				"%pcent% دوست داشتن", // new
RATING_NO_DATA:				"رتبه بندی در دسترس نیست." // new
},
// Suomi (Finnish)
"fi": {
PREFERENCES:				"Asetukset...",
DOWNLOAD_VIDEO:				"Lataa video",
DOWNLOAD_EMPTY:				"(tyhjä)",
DOWNLOAD_EMPTY_TIP:			"Tiedot voi ladata ei löytynyt",
DOWNLOAD_UNKNOWN_TIP:		"tuntematon videoformaatti",
STEP_FRAME_FORWARD:			"Askel yhden ruudun eteenpäin",
SEEK_FORWARD:				"Siirtyä eteenpäin",
SEEK_BACK:					"Hakea takaisin",
POPOUT_PLAYER:				"Näytä vain video",
LOOP_DISABLE:				"Poistaa silmukka",
LOOP_ENABLE:				"Jotta silmukka",
LOOP_SECTION_DISABLE:		"Poistaa osa silmukka",
LOOP_SECTION_ENABLE:		"Mahdollistavat osa silmukka",
LOOP_MARK_START:			"Merkki jakso alkaa",
LOOP_MARK_END:				"Merkki osa lopussa",
PREVIEW_START:				"Napsauta Käynnistä videon esikatselun.",
PREVIEW_END:				"Klikkaa loppuun videon esikatselun.",
LYRICS_BUTTON_HIDE:			"Piilota lyriikat",
LYRICS_BUTTON_SHOW:			"Selviää lyriikat",
LYRICS_BUTTON_LOAD:			"Kuormitus",
LYRICS_BUTTON_TRY:			"Kokeile itse...",
LYRICS_LYRICS:				"Lyriikat",
LYRICS_LYRICS_FOR:			"Lyriikat for: %song",
LYRICS_TITLE_INFO:			"Lisää taiteilijan nimi ja laulun etsiä.",
LYRICS_TITLE_INFO_EX:		"Erillinen on yhdysmerkki (esimerkiksi näin: Artist - osasto).",
LYRICS_SEARCH_START:		"Haetaan ”%song”...",
LYRICS_SEARCH_NO_RESULT:	"Ei tuloksia ”%song”.",
LYRICS_SEARCH_FOUND:		"Lyriikat löytynyt. Lastaus...",
LYRICS_SEARCH_NOT_FOUND:	"Lyriikat eivät löytynyt ja enää yhdistelmiä kokeilla.",
LYRICS_PARSE_SEARCH:		"Jäsentäminen hakutulosta...",
LYRICS_PARSE_LYRICS:		"Jäsentäminen lyrics tietoja...",
LYRICS_PARSE_SUCCESS:		"Lyriikat onnistuneesti käsitellä.",
LYRICS_PARSE_ERROR:			"Lyriikat are found mutta ei voi jäsentää. Anteeksi.",
LYRICS_TITLE_INVALID:		"Videon otsikko ei vastaa ”Artist - osasto” malli!",
RATING_LIKE:				"%pcent% pitää",
RATING_NO_DATA:				"Arvostelu ei ole saatavilla."
},
// Français (French)
//	Thanks to:
//		Alban Lemaitre <alban.roger.lemaitre@gmail.com>
//		Valentin Chemiere <vchemiere@gmail.com>
//		Guillaume Navet <guinavet@gmail.com>
"fr": {
PREFERENCES:				"Préférences...",
DOWNLOAD_VIDEO:				"Télécharger la vidéo",
DOWNLOAD_EMPTY:				"(vide)",
DOWNLOAD_EMPTY_TIP:			"Données de téléchargement non trouvées",
DOWNLOAD_UNKNOWN_TIP:		"format vidéo inconnue", // new
STEP_FRAME_FORWARD:			"Etape suivante",
SEEK_FORWARD:				"Suivant",
SEEK_BACK:					"Retour",
POPOUT_PLAYER:				"Accent vidéo", // new
LOOP_DISABLE:				"Désactiver la boucle",
LOOP_ENABLE:				"Activer la boucle",
LOOP_SECTION_DISABLE:		"Désactiver la lecture en boucle d’une sélection",
LOOP_SECTION_ENABLE:		"Activer la lecture en boucle d’une sélection",
LOOP_MARK_START:			"La boucle a debutee",
LOOP_MARK_END:				"La boucle s’est arretee",
PREVIEW_START:				"Cliquez ici pour démarrer prévisualisation vidéo.", // new
PREVIEW_END:				"Cliquez pour mettre fin à de prévisualisation vidéo.", // new
LYRICS_BUTTON_HIDE:			"Cacher les paroles",
LYRICS_BUTTON_SHOW:			"Afficher les paroles",
LYRICS_BUTTON_LOAD:			"Charger",
LYRICS_BUTTON_TRY:			"Veuillez essayer manuellement",
LYRICS_LYRICS:				"Paroles",
LYRICS_LYRICS_FOR:			"Paroles pour: %song",
LYRICS_TITLE_INFO:			"Insérer un artiste ou un titre de chanson pour le chercher.",
LYRICS_TITLE_INFO_EX:		"Séparé par un trait d’union (tel que: Artiste - Titre).",
LYRICS_SEARCH_START:		"Recherche pour « %song »...",
LYRICS_SEARCH_NO_RESULT:	"Pas de résultats pour « %song ».",
LYRICS_SEARCH_FOUND:		"Paroles trouvees. Veuillez patienter...",
LYRICS_SEARCH_NOT_FOUND:	"Paroles non trouvees. Toutes les combinaisons possibles ont etes essayees.",
LYRICS_PARSE_SEARCH:		"Analyse des résultats en cours...",
LYRICS_PARSE_LYRICS:		"Analyse des donnees des paroles en cours...",
LYRICS_PARSE_SUCCESS:		"Paroles analysées avec succès.",
LYRICS_PARSE_ERROR:			"Paroles trouvees mais ne peuvent etre analysees. Desole et merci de votre compréhension.",
LYRICS_TITLE_INVALID:		"Le titre de la video ne correspond pas au modèle « Artiste - Titre ».",
RATING_LIKE:				"%pcent% aiment", // new
RATING_NO_DATA:				"Note pas disponibles." // new
},
// Galego (Galician)
"gl": {
PREFERENCES:				"Preferencias...",
DOWNLOAD_VIDEO:				"Video descarga",
DOWNLOAD_EMPTY:				"(baleiro)",
DOWNLOAD_EMPTY_TIP:			"Datos para descargar Non se atopou",
DOWNLOAD_UNKNOWN_TIP:		"formato de vídeo descoñecida",
STEP_FRAME_FORWARD:			"Paso un cadro para adiante",
SEEK_FORWARD:				"Buscar cara adiante",
SEEK_BACK:					"Buscar de novo",
POPOUT_PLAYER:				"Pop out reprodutor de vídeo",
LOOP_DISABLE:				"Desactivar circuíto",
LOOP_ENABLE:				"Activar lazo",
LOOP_SECTION_DISABLE:		"Desactivar circuíto sección",
LOOP_SECTION_ENABLE:		"Activar circuíto sección",
LOOP_MARK_START:			"Mark comezar a sección",
LOOP_MARK_END:				"Mark sección final",
PREVIEW_START:				"Preme aquí para comezar a vista previa de vídeo.",
PREVIEW_END:				"Preme aquí para finais de visualización de vídeo.",
LYRICS_BUTTON_HIDE:			"Ocultar letras",
LYRICS_BUTTON_SHOW:			"Letras mostran",
LYRICS_BUTTON_LOAD:			"Carga",
LYRICS_BUTTON_TRY:			"Probe a man...",
LYRICS_LYRICS:				"Letra",
LYRICS_LYRICS_FOR:			"Letra da música: %song",
LYRICS_TITLE_INFO:			"Inserir artista eo título da canción para investigar.",
LYRICS_TITLE_INFO_EX:		"Separadas por guión (como así: Artista - Título).",
LYRICS_SEARCH_START:		"Buscando por «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Non hai resultados para «%song».",
LYRICS_SEARCH_FOUND:		"Letra atopado. Carga...",
LYRICS_SEARCH_NOT_FOUND:	"Letras non se atopan e non máis combinacións para probar.",
LYRICS_PARSE_SEARCH:		"Analizar os resultados da procura...",
LYRICS_PARSE_LYRICS:		"Análise de datos letras...",
LYRICS_PARSE_SUCCESS:		"Letras analizado correctamente.",
LYRICS_PARSE_ERROR:			"Letras se atopan, pero non pode ser analizado. Sentímolo.",
LYRICS_TITLE_INVALID:		"Título do vídeo non corresponde «Artista - Título» por defecto!",
RATING_LIKE:				"%pcent% «Gústame»",
RATING_NO_DATA:				"Avaliación de vídeo non está dispoñible."
},
// ગુજરાતી (Gujarati)
"gu": {
PREFERENCES:				"પસંદગીઓ...",
DOWNLOAD_VIDEO:				"વિડીયો ડાઉનલોડ કરો",
DOWNLOAD_EMPTY:				"(ખાલી)",
DOWNLOAD_EMPTY_TIP:			"મળ્યું નથી ડાઉનલોડ માટે માહિતી",
DOWNLOAD_UNKNOWN_TIP:		"અજ્ઞાત વિડિયો રચના",
STEP_FRAME_FORWARD:			"એક ફ્રેમ આગળ વધે",
SEEK_FORWARD:				"આગળ શોધો",
SEEK_BACK:					"પાછા શોધો",
POPOUT_PLAYER:				"બહાર વિડિયો પ્લેયર પૉપ",
LOOP_DISABLE:				"લૂપ નિષ્ક્રિય કરો",
LOOP_ENABLE:				"લૂપ સક્રિય કરો",
LOOP_SECTION_DISABLE:		"વિભાગ લૂપ નિષ્ક્રિય કરો",
LOOP_SECTION_ENABLE:		"વિભાગ લૂપ સક્રિય કરો",
LOOP_MARK_START:			"માર્ક વિભાગ શરૂ",
LOOP_MARK_END:				"માર્ક વિભાગમાં અંત",
PREVIEW_START:				"વીડિયો પૂર્વદર્શન શરૂ કરો ક્લિક કરો.",
PREVIEW_END:				"વીડિયો પૂર્વદર્શન અંત કરો ક્લિક કરો.",
LYRICS_BUTTON_HIDE:			"ગીતો છુપાવો",
LYRICS_BUTTON_SHOW:			"ગીતો બતાવો",
LYRICS_BUTTON_LOAD:			"લોડ કરો",
LYRICS_BUTTON_TRY:			"જાતે જ કરવાનો પ્રયાસ કરો...",
LYRICS_LYRICS:				"ગીતો",
LYRICS_LYRICS_FOR:			"માટે ગીતો: %song",
LYRICS_TITLE_INFO:			"કલાકાર અને શીર્ષક ગીત માટે શોધવા માટે દાખલ કરો.",
LYRICS_TITLE_INFO_EX:		"આડંબર (શીર્ષક - કલાકાર) સાથે અલગ પાડો.",
LYRICS_SEARCH_START:		"\"%song\" માટે શોધી રહ્યું છે...",
LYRICS_SEARCH_NO_RESULT:	"\"%song\" માટે કોઈ પરિણામ છે.",
LYRICS_SEARCH_FOUND:		"ગીતો જોવા મળે છે. લોડ...",
LYRICS_SEARCH_NOT_FOUND:	"ગીતકારઃ મળી નથી અને કોઈ વધુ સંયોજનો પ્રયાસ કરવામાં આવે છે.",
LYRICS_PARSE_SEARCH:		"શોધ પરિણામો પદચ્છેદન કરી રહ્યા છીએ...",
LYRICS_PARSE_LYRICS:		"ગીતો માહિતી પદચ્છેદન કરી રહ્યા છીએ...",
LYRICS_PARSE_SUCCESS:		"ગીતકારઃ સફળતાપૂર્વક પદચ્છેદન.",
LYRICS_PARSE_ERROR:			"ગીતકારઃ મળી પરંતુ આવે પાર્સ કરી શકો છો. માફ કરશો.",
LYRICS_TITLE_INVALID:		"વિડિઓ શીર્ષક \"આર્ટિસ્ટ - શીર્ષક\" બંધબેસે નહિં પેટર્ન!",
RATING_LIKE:				"%pcent% જેમ",
RATING_NO_DATA:				"ઉપલબ્ધ નથી પ્રતિસાદ."
},
// עברית (Hebrew)
"he": {
PREFERENCES:				"העדפות...",
DOWNLOAD_VIDEO:				"וידאו להורדה",
DOWNLOAD_EMPTY:				"(ריק)",
DOWNLOAD_EMPTY_TIP:			"נתונים להורדה לא נמצאו",
DOWNLOAD_UNKNOWN_TIP:		"וידאו בפורמט לא ידוע",
STEP_FRAME_FORWARD:			"צעד אחד קדימה מסגרת",
SEEK_FORWARD:				"מחפשים קדימה",
SEEK_BACK:					"לחפש לאחור",
POPOUT_PLAYER:				"פופ החוצה נגן וידאו",
LOOP_DISABLE:				"להשבית את הלולאה",
LOOP_ENABLE:				"להפעיל לולאה",
LOOP_SECTION_DISABLE:		"בסעיף להשבית לולאה",
LOOP_SECTION_ENABLE:		"להפעיל לולאה בסעיף",
LOOP_MARK_START:			"בסעיף סימן להתחיל",
LOOP_MARK_END:				"בסעיף סימן לסוף",
PREVIEW_START:				"לחץ כדי להפעיל את התצוגה המקדימה וידאו.",
PREVIEW_END:				"לחץ לסיים את התצוגה המקדימה וידאו.",
LYRICS_BUTTON_HIDE:			"להסתיר מילים",
LYRICS_BUTTON_SHOW:			"הצג מילים",
LYRICS_BUTTON_LOAD:			"עומס",
LYRICS_BUTTON_TRY:			"נסה באופן ידני...",
LYRICS_LYRICS:				"מילים",
LYRICS_LYRICS_FOR:			"מילים: %song",
LYRICS_TITLE_INFO:			"האמן הוספה הכותרת של השיר כדי לחפש.",
LYRICS_TITLE_INFO_EX:		"להפריד על ידי מקף (כמו כל כך: אמן - כותרת).",
LYRICS_SEARCH_START:		"מחפש “%song”...",
LYRICS_SEARCH_NO_RESULT:	"אין תוצאות עבור “%song”.",
LYRICS_SEARCH_FOUND:		"מילים נמצאו. טוען...",
LYRICS_SEARCH_NOT_FOUND:	"מילים לא נמצאים ואין שילובים יותר לנסות.",
LYRICS_PARSE_SEARCH:		"תוצאות החיפוש של ניתוח...",
LYRICS_PARSE_LYRICS:		"ניתוח הנתונים מילים...",
LYRICS_PARSE_SUCCESS:		"מילים מנותח בהצלחה.",
LYRICS_PARSE_ERROR:			"מילים הם מצאו, אבל לא יכול להיות מנותח. סליחה.",
LYRICS_TITLE_INVALID:		"שם הקליפ אינו תואם “אמן - כותרת” דפוס!",
RATING_LIKE:				"%pcent% אהבתי",
RATING_NO_DATA:				"לא זמין דירוג."
},
// हिन्दी (Hindi)
"hi": {
PREFERENCES:				"वरीयता...",
DOWNLOAD_VIDEO:				"डाउनलोड वीडियो",
DOWNLOAD_EMPTY:				"(खाली)",
DOWNLOAD_EMPTY_TIP:			"नहीं मिला डाउनलोड के लिए डेटा",
DOWNLOAD_UNKNOWN_TIP:		"अज्ञात वीडियो प्रारूप",
STEP_FRAME_FORWARD:			"एक कदम आगे फ्रेम",
SEEK_FORWARD:				"आगे की तलाश",
SEEK_BACK:					"पीठ की तलाश",
POPOUT_PLAYER:				"बाहर वीडियो प्लेयर पॉप",
LOOP_DISABLE:				"निष्क्रिय पाश",
LOOP_ENABLE:				"पाश सक्षम",
LOOP_SECTION_DISABLE:		"निष्क्रिय अनुभाग पाश",
LOOP_SECTION_ENABLE:		"अनुभाग पाश सक्षम",
LOOP_MARK_START:			"निशान खंड शुरू",
LOOP_MARK_END:				"चिह्न अनुभाग अंत",
PREVIEW_START:				"वीडियो पूर्वावलोकन शुरू करने के लिए क्लिक करें.",
PREVIEW_END:				"वीडियो पूर्वावलोकन को समाप्त करने के लिए क्लिक करें.",
LYRICS_BUTTON_HIDE:			"गीत छिपाना",
LYRICS_BUTTON_SHOW:			"दिखाने के गीत",
LYRICS_BUTTON_LOAD:			"भार",
LYRICS_BUTTON_TRY:			"मैन्युअल रूप से प्रयास करें...",
LYRICS_LYRICS:				"गीत",
LYRICS_LYRICS_FOR:			"के लिए गीत: %song",
LYRICS_TITLE_INFO:			"सम्मिलित कलाकार और गीत के शीर्षक के लिए खोज करने के लिए.",
LYRICS_TITLE_INFO_EX:		"हायफ़न द्वारा अलग तरह (इतने: कलाकार - शीर्षक).",
LYRICS_SEARCH_START:		"खोज के लिए “%song”...",
LYRICS_SEARCH_NO_RESULT:	"के लिए कोई परिणाम नहीं “%song”.",
LYRICS_SEARCH_FOUND:		"बोल पाया. लोड हो रहा है...",
LYRICS_SEARCH_NOT_FOUND:	"बोल पाया और न कोई और अधिक संयोजनों की कोशिश कर रहे हैं.",
LYRICS_PARSE_SEARCH:		"पार्सिंग खोज परिणाम...",
LYRICS_PARSE_LYRICS:		"पार्सिंग गीत डेटा...",
LYRICS_PARSE_SUCCESS:		"गीत को सफलतापूर्वक विश्लेषित.",
LYRICS_PARSE_ERROR:			"गीत मिल रहे हैं, लेकिन विश्लेषित नहीं कर सकते हैं. माफ़ कीजिए.",
LYRICS_TITLE_INVALID:		"पैटर्न - वीडियो शीर्षक “शीर्षक कलाकार ” से मेल नहीं खाता!",
RATING_LIKE:				"%pcent% पसंद",
RATING_NO_DATA:				"रेटिंग नहीं उपलब्ध है."
},
// Hrvatski (Croatian)
//	Thanks to: me :), Darko Pantić
"hr": {
PREFERENCES:				"Postavke...",
DOWNLOAD_VIDEO:				"Preuzimanje video datotekе",
DOWNLOAD_EMPTY:				"(prazno)",
DOWNLOAD_EMPTY_TIP:			"Podaci za preuzimanje nisu pronađeni",
DOWNLOAD_UNKNOWN_TIP:		"nepoznat video format",
STEP_FRAME_FORWARD:			"Korak naprijed jedan okvir",
SEEK_FORWARD:				"Skoči naprijed",
SEEK_BACK:					"Skoči nazad",
POPOUT_PLAYER:				"Prikaži samo video",
LOOP_DISABLE:				"Onemogućit petlju",
LOOP_ENABLE:				"Omogućit petlju",
LOOP_SECTION_DISABLE:		"Onemogućit dio petlje",
LOOP_SECTION_ENABLE:		"Omogućit dio petlje",
LOOP_MARK_START:			"Obilježi početak odjeljaka",
LOOP_MARK_END:				"Obilježi kraj odjeljaka",
PREVIEW_START:				"Kliknite da počnete pregled videa.",
PREVIEW_END:				"Kliknite da završite pregled videa.",
LYRICS_BUTTON_HIDE:			"Sakrij tekst pjesme",
LYRICS_BUTTON_SHOW:			"Prikaži tekst pjesme",
LYRICS_BUTTON_LOAD:			"Učitaj",
LYRICS_BUTTON_TRY:			"Pokušajte ručno...",
LYRICS_LYRICS:				"Tekst pjesme",
LYRICS_LYRICS_FOR:			"Tekst za pjesmu: %song",
LYRICS_TITLE_INFO:			"Umetnite izvođaču i naslov pjesme za pretraživanje.",
LYRICS_TITLE_INFO_EX:		"Odvojeni po crticu (kao što su to: Artist - Title).",
LYRICS_SEARCH_START:		"U potrazi za „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Nema rezultata za „%song“.",
LYRICS_SEARCH_FOUND:		"Tekst pjesme pronađen. Učitavanje...",
LYRICS_SEARCH_NOT_FOUND:	"Tekst pjesme nije pronađen i nema više kombinacija probati.",
LYRICS_PARSE_SEARCH:		"Raščlanjivanje rezultata pretraživanja...",
LYRICS_PARSE_LYRICS:		"Raščlanjivanje podataka teksta pjesme...",
LYRICS_PARSE_SUCCESS:		"Tekst pjesme uspješno analiziran.",
LYRICS_PARSE_ERROR:			"Tekst pjesme je nađen, ali ne mogu se raščlaniti. Oprostite.",
LYRICS_TITLE_INVALID:		"Video naslov ne odgovara „Artist - Title“ uzorku!",
RATING_LIKE:				"Sviđa se: %pcent%",
RATING_NO_DATA:				"Ocjena nije dostupna."
},
// Magyar (Hungarian)
//	Thanks to:
//		Molnár Tibor <mtibee@gmail.com>
"hu": {
PREFERENCES:				"Beállítások...",
DOWNLOAD_VIDEO:				"Videó letöltése",
DOWNLOAD_EMPTY:				"(üres)",
DOWNLOAD_EMPTY_TIP:			"Nincs letölthető adat",
DOWNLOAD_UNKNOWN_TIP:		"ismeretlen videó formátum", // new
STEP_FRAME_FORWARD:			"Léptetés egy képkockával elõre",
SEEK_FORWARD:				"Elõre tekerés",
SEEK_BACK:					"Hátra tekerés",
POPOUT_PLAYER:				"Mutasd csak videó", // new
LOOP_DISABLE:				"Ismétlés kikapcsolása",
LOOP_ENABLE:				"Ismétlés bekapcsolása",
LOOP_SECTION_DISABLE:		"Szakasz ismétlésének kikapcsolása",
LOOP_SECTION_ENABLE:		"Szakasz ismétlésének bekapcsolása",
LOOP_MARK_START:			"Szakasz kezdõpontjának kijelölése",
LOOP_MARK_END:				"Szakasz végpontjának kijelölése",
PREVIEW_START:				"Klikkelj hogy video preview.", // new
PREVIEW_END:				"Kattints ide a végére video preview.", // new
LYRICS_BUTTON_HIDE:			"Dalszöveg elrejtése",
LYRICS_BUTTON_SHOW:			"Dalszöveg megjelenítése",
LYRICS_BUTTON_LOAD:			"Betöltés",
LYRICS_BUTTON_TRY:			"Próbáld manuálisan...",
LYRICS_LYRICS:				"Dalszöveg",
LYRICS_LYRICS_FOR:			"Dalszöveg ehhez: %song",
LYRICS_TITLE_INFO:			"Gépeld be az elõadót és a szám címét, amire keresel!",
LYRICS_TITLE_INFO_EX:		"Válaszd el kötõjellel (Így: Elõadó - Cím)!",
LYRICS_SEARCH_START:		"Keresés: „%song”...",
LYRICS_SEARCH_NO_RESULT:	"Nincs eredmény erre: „%song”.",
LYRICS_SEARCH_FOUND:		"Dalszöveget találtam. Betöltés...",
LYRICS_SEARCH_NOT_FOUND:	"Nem találtam dalszöveget. Nincs több lehetõséged próbálkozni.",
LYRICS_PARSE_SEARCH:		"A keresés eredményeinek nyelvtani elemzése...",
LYRICS_PARSE_LYRICS:		"Dalszövegek nyelvtani elemzése...",
LYRICS_PARSE_SUCCESS:		"A dalszövegek nyelvtani elemzése sikeres.",
LYRICS_PARSE_ERROR:			"Találtam dalszöveget, de a nyelvi elemzése nem végezhetõ el. Sajnálom.",
LYRICS_TITLE_INVALID:		"A videó címe nem egyezik az „Elõadó - Cím” mintával!",
RATING_LIKE:				"%pcent% embernek tetszik", // new
RATING_NO_DATA:				"Értékelés nem elérhető." // new
},
// Bahasa Indonesia (Indonesian)
"id": {
PREFERENCES:				"Preferensi...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(kosong)",
DOWNLOAD_EMPTY_TIP:			"Data untuk download tidak ditemukan",
DOWNLOAD_UNKNOWN_TIP:		"diketahui format video",
STEP_FRAME_FORWARD:			"Langkah maju satu frame",
SEEK_FORWARD:				"Mencari maju",
SEEK_BACK:					"Mencari kembali",
POPOUT_PLAYER:				"Tampilkan video saja",
LOOP_DISABLE:				"Menonaktifkan loop",
LOOP_ENABLE:				"Memungkinkan loop",
LOOP_SECTION_DISABLE:		"Menonaktifkan bagian loop",
LOOP_SECTION_ENABLE:		"Memungkinkan loop bagian",
LOOP_MARK_START:			"Menandai bagian awal",
LOOP_MARK_END:				"Menandai bagian akhir",
PREVIEW_START:				"Klik untuk memulai video preview.",
PREVIEW_END:				"Klik untuk mengakhiri preview video.",
LYRICS_BUTTON_HIDE:			"Menyembunyikan lirik",
LYRICS_BUTTON_SHOW:			"Menunjukkan lirik",
LYRICS_BUTTON_LOAD:			"Beban",
LYRICS_BUTTON_TRY:			"Coba secara manual...",
LYRICS_LYRICS:				"Lirik",
LYRICS_LYRICS_FOR:			"Lirik untuk: %song",
LYRICS_TITLE_INFO:			"Masukkan artis dan judul lagu untuk mencari.",
LYRICS_TITLE_INFO_EX:		"Pisahkan dengan tanda hubung (seperti: Artis - Judul).",
LYRICS_SEARCH_START:		"Mencari “%song”...",
LYRICS_SEARCH_NO_RESULT:	"Tidak ada hasil untuk “%song”.",
LYRICS_SEARCH_FOUND:		"Lirik ditemukan. Pembebanan...",
LYRICS_SEARCH_NOT_FOUND:	"Lirik yang tidak ditemukan dan tidak ada kombinasi yang lebih banyak untuk mencoba.",
LYRICS_PARSE_SEARCH:		"Parsing hasil penelusuran...",
LYRICS_PARSE_LYRICS:		"Parsing lyrics data...",
LYRICS_PARSE_SUCCESS:		"Lirik berhasil dipecah.",
LYRICS_PARSE_ERROR:			"Lirik yang ditemukan tetapi tidak bisa diurai. Maaf.",
LYRICS_TITLE_INVALID:		"Video judul tidak cocok “Artis - Judul” Pola!",
RATING_LIKE:				"%pcent% suka",
RATING_NO_DATA:				"Penilaian tidak tersedia."
},
// Íslenska (Icelandic)
"is": {
PREFERENCES:				"Preferences...",
DOWNLOAD_VIDEO:				"Sækja vídeó",
DOWNLOAD_EMPTY:				"(tóm)",
DOWNLOAD_EMPTY_TIP:			"Gögn fyrir download fannst ekki",
DOWNLOAD_UNKNOWN_TIP:		"óþekkt vídeó snið",
STEP_FRAME_FORWARD:			"Skref einn ramma áfram",
SEEK_FORWARD:				"Leitið áfram",
SEEK_BACK:					"Leitið til baka",
POPOUT_PLAYER:				"Pop út vídeó leikmaður",
LOOP_DISABLE:				"Gera óvinnufæran lykkja",
LOOP_ENABLE:				"Virkja lykkja",
LOOP_SECTION_DISABLE:		"Gera óvinnufæran hluta lykkja",
LOOP_SECTION_ENABLE:		"Virkja hluta lykkja",
LOOP_MARK_START:			"Mark lið byrja",
LOOP_MARK_END:				"Mark kafla enda",
PREVIEW_START:				"Smelltu til að byrja vídeó forsýning.",
PREVIEW_END:				"Smelltu til endir vídeó forsýning.",
LYRICS_BUTTON_HIDE:			"Fela lyrics",
LYRICS_BUTTON_SHOW:			"Show lyrics",
LYRICS_BUTTON_LOAD:			"Hlaða",
LYRICS_BUTTON_TRY:			"Prófaðu handvirkt...",
LYRICS_LYRICS:				"Lyrics",
LYRICS_LYRICS_FOR:			"Lyrics for: %song",
LYRICS_TITLE_INFO:			"Setja listamaður og titill lag til að leita að.",
LYRICS_TITLE_INFO_EX:		"Aðskilja með bandstrik (eins og svo: Artist - Title).",
LYRICS_SEARCH_START:		"Leitað að „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Engar niðurstöður fyrir „%song“.",
LYRICS_SEARCH_FOUND:		"Lyrics fundust. Loading...",
LYRICS_SEARCH_NOT_FOUND:	"Lyrics er ekki að finna og ekki fleiri samsetningar til að reyna.",
LYRICS_PARSE_SEARCH:		"Þátta leitarniðurstöður...",
LYRICS_PARSE_LYRICS:		"Þátta Lyrics gögn...",
LYRICS_PARSE_SUCCESS:		"Lyrics flokka með góðum árangri.",
LYRICS_PARSE_ERROR:			"Lyrics finnast en ekki er hægt að flokka. Því miður.",
LYRICS_TITLE_INVALID:		"Video titill passar ekki „Artist - Titill“ mynstur!",
RATING_LIKE:				"%pcent% líkar þetta",
RATING_NO_DATA:				"Stjörnugjöf ekki í boði."
},
// Italiano (Italian)
//	Thanks to:
//		Francesco Parente <frenk_91@hotmail.it>
//		Emanuele Buda
"it": {
PREFERENCES:				"Preferenze...",
DOWNLOAD_VIDEO:				"Scarica video",
DOWNLOAD_EMPTY:				"(vuoto)",
DOWNLOAD_EMPTY_TIP:			"Non è stato trovato niente da scaricare",
DOWNLOAD_UNKNOWN_TIP:		"video formato sconosciuto", // new
STEP_FRAME_FORWARD:			"Avanti di un frame",
SEEK_FORWARD:				"Avanti velose",
SEEK_BACK:					"Indietro veloce",
POPOUT_PLAYER:				"Mostra solo video", // new
LOOP_DISABLE:				"Disattiva ripetizione",
LOOP_ENABLE:				"Attiva ripetizione",
LOOP_SECTION_DISABLE:		"Disattiva ripetizione della selezione",
LOOP_SECTION_ENABLE:		"Attiva ripetizione della selezione",
LOOP_MARK_START:			"Imposta inizio selezione",
LOOP_MARK_END:				"Imposta fine selezione",
PREVIEW_START:				"Fare clic per avviare anteprima video.", // new
PREVIEW_END:				"Clicca per fine di anteprima video.", // new
LYRICS_BUTTON_HIDE:			"Nascondi il testo della canzone",
LYRICS_BUTTON_SHOW:			"Visualizza il testo della canzone",
LYRICS_BUTTON_LOAD:			"Carica",
LYRICS_BUTTON_TRY:			"Prova manualmente...",
LYRICS_LYRICS:				"Testo della canzone",
LYRICS_LYRICS_FOR:			"Testo della canzone per: %song",
LYRICS_TITLE_INFO:			"Inserisci artista e titolo della canzone che stai cercando.",
LYRICS_TITLE_INFO_EX:		"Separati da un trattino (ad esempio: Artista - Titolo).",
LYRICS_SEARCH_START:		"Ricerca per «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Nessun risultato per «%song».",
LYRICS_SEARCH_FOUND:		"Testo trovato. In caricamento...",
LYRICS_SEARCH_NOT_FOUND:	"Testo non trovato, non ci sono più combinazioni possibili.",
LYRICS_PARSE_SEARCH:		"Analisi del risultato...",
LYRICS_PARSE_LYRICS:		"Analisi del testo in corso...",
LYRICS_PARSE_SUCCESS:		"Testo correttamente analizzato.",
LYRICS_PARSE_ERROR:			"Il testo è stato trovato ma non è stato possibile analizzarlo. Spiacenti.",
LYRICS_TITLE_INVALID:		"Il titolo del video non corrisponde «Artista - Titolo» percorso!",
RATING_LIKE:				"%pcent% Mi piace", // new
RATING_NO_DATA:				"Categoria non disponibile." // new
},
// 日本語 (Japanese)
//	Thanks to:
//		ka106_56 <kat465a@live.jp>
"ja": {
PREFERENCES:				"設定...",
DOWNLOAD_VIDEO:				"ビデオをダウンロード",
DOWNLOAD_EMPTY:				"（空）",
DOWNLOAD_EMPTY_TIP:			"ダウンロード用のデータが見つかりませんでした",
DOWNLOAD_UNKNOWN_TIP:		"不明なビデオフォーマット",
STEP_FRAME_FORWARD:			"一歩前進つのフレーム",
SEEK_FORWARD:				"前方にシーク",
SEEK_BACK:					"後方にシーク",
POPOUT_PLAYER:				"ビデオのみを表示する", // new
LOOP_DISABLE:				"ループを無効にする",
LOOP_ENABLE:				"ループを有効にする",
LOOP_SECTION_DISABLE:		"ループを無効にする",
LOOP_SECTION_ENABLE:		"ループを有効にする",
LOOP_MARK_START:			"ループ開始点を設定",
LOOP_MARK_END:				"ループ終了点を設定",
PREVIEW_START:				"ビデオのプレビューを開始するときにクリックします。", // new
PREVIEW_END:				"ビデオのプレビューを終了する]をクリックします。", // new
LYRICS_BUTTON_HIDE:			"歌詞を非表示にする",
LYRICS_BUTTON_SHOW:			"歌詞を表示する",
LYRICS_BUTTON_LOAD:			"読み込む",
LYRICS_BUTTON_TRY:			"手動で読み込みを試みる...",
LYRICS_LYRICS:				"歌詞",
LYRICS_LYRICS_FOR:			"表示中の歌詞： %song",
LYRICS_TITLE_INFO:			"[挿入]アーティストや曲のタイトルが検索できます。",
LYRICS_TITLE_INFO_EX:		"ハイフンで区切ってください（例：アーティスト-タイトル）。",
LYRICS_SEARCH_START:		"次を検索 「%song」...",
LYRICS_SEARCH_NO_RESULT:	"次の曲に対する検索結果は見つかりませんでした 「%song」.",
LYRICS_SEARCH_FOUND:		"歌詞が見つかりました。読み込んでいます...",
LYRICS_SEARCH_NOT_FOUND:	"歌詞が見つかりませんでした。その他の組み合わせを試しています。",
LYRICS_PARSE_SEARCH:		"歌詞の解析による検索結果...",
LYRICS_PARSE_LYRICS:		"解析済み歌詞データ...",
LYRICS_PARSE_SUCCESS:		"歌詞は正常に解析されました。",
LYRICS_PARSE_ERROR:			"歌詞は見つかりましたが、解析できません。申し訳ありません。",
LYRICS_TITLE_INVALID:		"ビデオタイトルが次の組み合わせで一致しませんでした。 「Artist - Title」",
RATING_LIKE:				"高評価 %pcent%", // new
RATING_NO_DATA:				"利用できない評価。" // new
},
// ಕನ್ನಡ (Kannada)
"kn": {
PREFERENCES:				"ಆಯ್ಕೆಗಳು...",
DOWNLOAD_VIDEO:				"ವಿಡಿಯೋ ಡೌನ್ಲೋಡ್",
DOWNLOAD_EMPTY:				"(ಖಾಲಿ)",
DOWNLOAD_EMPTY_TIP:			"ಡೌನ್ಲೋಡ್ ಮಾಹಿತಿ ಕಂಡುಬಂದಿಲ್ಲ",
DOWNLOAD_UNKNOWN_TIP:		"ಅಜ್ಞಾತ ವಿಡಿಯೋ ಸ್ವರೂಪದ",
STEP_FRAME_FORWARD:			"ಮುಂದೆ ಒಂದು ಫ್ರೇಮ್ ಸ್ಟೆಪ್",
SEEK_FORWARD:				"ಮುಂದೆ ಅನ್ವೇಷಿಸು",
SEEK_BACK:					"ಮತ್ತೆ ಅನ್ವೇಷಿಸು",
POPOUT_PLAYER:				"ವಿಡಿಯೋ ಪ್ಲೇಯರ್ ಪಾಪ್ ಔಟ್",
LOOP_DISABLE:				"ಲೂಪ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ",
LOOP_ENABLE:				"ಲೂಪ್ ಸಕ್ರಿಯಗೊಳಿಸಿ",
LOOP_SECTION_DISABLE:		"ಭಾಗವನ್ನುತೆರೆದು ಲೂಪ್ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ",
LOOP_SECTION_ENABLE:		"ಭಾಗವನ್ನುತೆರೆದು ಲೂಪ್ ಸಕ್ರಿಯಗೊಳಿಸಿ",
LOOP_MARK_START:			"ಮಾರ್ಕ್ ಭಾಗವನ್ನುತೆರೆದು ಆರಂಭ",
LOOP_MARK_END:				"ಮಾರ್ಕ್ ಭಾಗವನ್ನುತೆರೆದು ಕೊನೆಯಲ್ಲಿ",
PREVIEW_START:				"ವೀಡಿಯೊ ಪೂರ್ವವೀಕ್ಷಣೆ ಆರಂಭಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ.",
PREVIEW_END:				"ವೀಡಿಯೊ ಪೂರ್ವವೀಕ್ಷಣೆ ಕೊನೆಗೊಂಡಿಲ್ಲ ಕ್ಲಿಕ್ ಮಾಡಿ.",
LYRICS_BUTTON_HIDE:			"ಸಾಹಿತ್ಯ ಮರೆಮಾಡಿ",
LYRICS_BUTTON_SHOW:			"ಸಾಹಿತ್ಯ ತೋರಿಸಿ",
LYRICS_BUTTON_LOAD:			"ಲೋಡ್",
LYRICS_BUTTON_TRY:			"ಕೈಯಾರೆ ಪ್ರಯತ್ನಿಸಿ...",
LYRICS_LYRICS:				"ಸಾಹಿತ್ಯ",
LYRICS_LYRICS_FOR:			"ಗೀತ: %song",
LYRICS_TITLE_INFO:			"ಕಲಾವಿದ ಮತ್ತು ಹುಡುಕಲು ಹಾಡಿನ ಶೀರ್ಷಿಕೆ ಸೇರಿಸಿ.",
LYRICS_TITLE_INFO_EX:		"ಕೂಡುಗೆರೆ (ಟೈಟಲ್ ತರಹ: ಕಲಾವಿದ - ಆದ್ದರಿಂದ) ಪ್ರತ್ಯೇಕ.",
LYRICS_SEARCH_START:		"\"%song\" ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
LYRICS_SEARCH_NO_RESULT:	"\"%song\" ಫಲಿತಾಂಶವನ್ನು ಇಲ್ಲ.",
LYRICS_SEARCH_FOUND:		"ಸಾಹಿತ್ಯ ಕಂಡುಬಂದಿಲ್ಲ. ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
LYRICS_SEARCH_NOT_FOUND:	"ಸಾಹಿತ್ಯ ಕಂಡುಬರುವುದಿಲ್ಲ ಮತ್ತು ಯಾವುದೇ ಸಂಯೋಜನೆಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
LYRICS_PARSE_SEARCH:		"ಹುಡುಕಾಟ ಫಲಿತಾಂಶಗಳನ್ನು ಪಾರ್ಸಿಂಗ್...",
LYRICS_PARSE_LYRICS:		"ಸಾಹಿತ್ಯ ದತ್ತಾಂಶ ಪಾರ್ಸಿಂಗ್...",
LYRICS_PARSE_SUCCESS:		"ಸಾಹಿತ್ಯ ಯಶಸ್ವಿಯಾಗಿ ಪಾರ್ಸ್.",
LYRICS_PARSE_ERROR:			"ಸಾಹಿತ್ಯ ಕಂಡುಬರುತ್ತವೆ ಆದರೆ ಪಾರ್ಸ್ ಸಾಧ್ಯವಿಲ್ಲ. ಕ್ಷಮಿಸಿ.",
LYRICS_TITLE_INVALID:		"ವೀಡಿಯೊ ಶೀರ್ಷಿಕೆ \"ಕಲಾವಿದ - ಶೀರ್ಷಿಕೆ\" ಹೊಂದುತ್ತಿಲ್ಲ ಮಾದರಿ!",
RATING_LIKE:				"%pcent% ನಂತಹ",
RATING_NO_DATA:				"ರೇಟಿಂಗ್ ಲಭ್ಯವಿಲ್ಲ."
},
// 한국어 (Korean)
"ko": {
PREFERENCES:				"환경 설정...",
DOWNLOAD_VIDEO:				"다운로드 동영상",
DOWNLOAD_EMPTY:				"(빈)",
DOWNLOAD_EMPTY_TIP:			"다운로드를위한 데이터를 찾을 수 없습니다",
DOWNLOAD_UNKNOWN_TIP:		"알려지지 않은 비디오 포맷",
STEP_FRAME_FORWARD:			"앞으로 단계 한 프레임",
SEEK_FORWARD:				"앞으로 탐색",
SEEK_BACK:					"뒤로 탐색",
POPOUT_PLAYER:				"비디오 플레이어를 팝",
LOOP_DISABLE:				"해제 루프",
LOOP_ENABLE:				"루프를 사용",
LOOP_SECTION_DISABLE:		"해제 섹션 루프",
LOOP_SECTION_ENABLE:		"섹션 루프를 사용",
LOOP_MARK_START:			"마크 섹션 시작",
LOOP_MARK_END:				"마크 섹션 끝",
PREVIEW_START:				"동영상 미리보기를 시작합니다.",
PREVIEW_END:				"비디오 미리보기를 종료합니다.",
LYRICS_BUTTON_HIDE:			"가사 숨기기",
LYRICS_BUTTON_SHOW:			"가사보기",
LYRICS_BUTTON_LOAD:			"하중",
LYRICS_BUTTON_TRY:			"수동으로 시도...",
LYRICS_LYRICS:				"가사",
LYRICS_LYRICS_FOR:			"가사 용: %song",
LYRICS_TITLE_INFO:			"삽입 아티스트와 노래 제목을 검색합니다.",
LYRICS_TITLE_INFO_EX:		"하이픈으로 구분 (가 마음 : 아티스트 - 타이틀).",
LYRICS_SEARCH_START:		"검색 중 “%song”...",
LYRICS_SEARCH_NO_RESULT:	"에 대한 검색 결과가 없습니다 “%song”.",
LYRICS_SEARCH_FOUND:		"가사가 없습니다. 로드 중입니다...",
LYRICS_SEARCH_NOT_FOUND:	"가사는 발견되지 더 이상의 조합을 시도합니다.",
LYRICS_PARSE_SEARCH:		"구문 분석 검색 결과...",
LYRICS_PARSE_LYRICS:		"파싱 ​​가사 데이터...",
LYRICS_PARSE_SUCCESS:		"가사가 성공적으로 구문 분석.",
LYRICS_PARSE_ERROR:			"가사하지만 발견되는 파싱할 수 없습니다. 미안 해요.",
LYRICS_TITLE_INVALID:		"패턴 - 비디오 제목은 “제목 아티스트”과 일치하지 않습니다!",
RATING_LIKE:				"좋아요 %pcent%개",
RATING_NO_DATA:				"등급을 사용할 수 없습니다."
},
// Lietuvių (Lithuanian)
//	Thanks to:
//		Aleksandras T. <aleksandrr@gmail.com>
"lt": {
PREFERENCES:				"Nustatymai...",
DOWNLOAD_VIDEO:				"Parsisiųsti",
DOWNLOAD_EMPTY:				"(tusčia)",
DOWNLOAD_EMPTY_TIP:			"Informacijos nerasta",
DOWNLOAD_UNKNOWN_TIP:		"nežinomas vaizdo formatas", // new
STEP_FRAME_FORWARD:			"Vienas kadras į priekį",
SEEK_FORWARD:				"Prasukti į priekį",
SEEK_BACK:					"Atsukti atgal",
POPOUT_PLAYER:				"Iššokti vaizdo grotuvas", // new
LOOP_DISABLE:				"Išjungti nepertraukiamą grojimą",
LOOP_ENABLE:				"Įjungti nepertraukiamą grojimą",
LOOP_SECTION_DISABLE:		"Išjungti atkarpos nepertraukiamą grojimą",
LOOP_SECTION_ENABLE:		"Įjungti atkarpos nepertraukiamą grojimą",
LOOP_MARK_START:			"Pažymėti atkarpos pradžią",
LOOP_MARK_END:				"Pažymėti atkarpos pabaigą",
PREVIEW_START:				"Spustelėkite, jei norite paleisti vaizdo peržiūros.", // new
PREVIEW_END:				"Spustelėkite, jei norite baigti vaizdo peržiūros.", // new
LYRICS_BUTTON_HIDE:			"Paslėpti tekstą",
LYRICS_BUTTON_SHOW:			"Rodyti tekstą",
LYRICS_BUTTON_LOAD:			"Užkrauti",
LYRICS_BUTTON_TRY:			"Pabandyti pačiam...",
LYRICS_LYRICS:				"Tekstas",
LYRICS_LYRICS_FOR:			"Tekstas: %song",
LYRICS_TITLE_INFO:			"Įveskite atlikėjo ir dainos pavadinimą paieškai.",
LYRICS_TITLE_INFO_EX:		"Atskirti brukšneliu (pvz.: Artist - Title).",
LYRICS_SEARCH_START:		"Ieškoma „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Rezultatų nerasta: „%song“.",
LYRICS_SEARCH_FOUND:		"Tekstas surastas. Kraunasi...",
LYRICS_SEARCH_NOT_FOUND:	"Tekstas nesurastas ir galimų kombinacijų nebeliko.",
LYRICS_PARSE_SEARCH:		"Analizuojami paieškos rezultatai...",
LYRICS_PARSE_LYRICS:		"Analizuojamas tekstas...",
LYRICS_PARSE_SUCCESS:		"Tekstas sėkmingai atpažintas.",
LYRICS_PARSE_ERROR:			"Tekstas rastas, bet negali būtų atpažintas. Atsiprašome.",
LYRICS_TITLE_INVALID:		"Pavadinimas neatitinka reikiamo formato „Artist - Title“!",
RATING_LIKE:				"%pcent% teig. įvertinim.", // new
RATING_NO_DATA:				"Vaizdo įvertinimas nėra." // new
},
// Latviešu valoda (Latvian)
"lv": {
PREFERENCES:				"Preferences...",
DOWNLOAD_VIDEO:				"Lejuplādēt video",
DOWNLOAD_EMPTY:				"(tukši)",
DOWNLOAD_EMPTY_TIP:			"Dati lejupielādei nav atrasts",
DOWNLOAD_UNKNOWN_TIP:		"nezināms video formātā",
STEP_FRAME_FORWARD:			"Solis uz viena rāmja priekšu",
SEEK_FORWARD:				"Meklētu uz priekšu",
SEEK_BACK:					"Meklētu atpakaļ",
POPOUT_PLAYER:				"Rādīt video tikai",
LOOP_DISABLE:				"Atslēgt cilpa",
LOOP_ENABLE:				"Lai cilpa",
LOOP_SECTION_DISABLE:		"Atslēgt sadaļā cilpa",
LOOP_SECTION_ENABLE:		"Lai sadaļa cilpa",
LOOP_MARK_START:			"Zīmi sadaļā sākums",
LOOP_MARK_END:				"Zīmi sadaļā beigām",
PREVIEW_START:				"Noklikšķiniet, lai sāktu video preview.",
PREVIEW_END:				"Noklikšķiniet, lai pārtrauktu video preview.",
LYRICS_BUTTON_HIDE:			"Paslēpt tekst",
LYRICS_BUTTON_SHOW:			"Rādīt tekst",
LYRICS_BUTTON_LOAD:			"Slodzes",
LYRICS_BUTTON_TRY:			"Mēģiniet manuāli...",
LYRICS_LYRICS:				"Tekst",
LYRICS_LYRICS_FOR:			"Teksta dziesmu: %song",
LYRICS_TITLE_INFO:			"Ievietojiet mākslinieks un dziesmu nosaukumu meklēt.",
LYRICS_TITLE_INFO_EX:		"Nošķirti defisi (piemēram, tā: Mākslinieks - sadaļa).",
LYRICS_SEARCH_START:		"Meklējot «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Nav rezultātu «%song».",
LYRICS_SEARCH_FOUND:		"Tekst atrasts. Iekraušanas...",
LYRICS_SEARCH_NOT_FOUND:	"Tekst nav atrasts, un ne vairāk kombinācijas izmēģināt.",
LYRICS_PARSE_SEARCH:		"Analizējot meklēšanas rezultāti...",
LYRICS_PARSE_LYRICS:		"Analizējot tekst datus...",
LYRICS_PARSE_SUCCESS:		"Tekst veiksmīgi parsēt.",
LYRICS_PARSE_ERROR:			"Tekst tiek konstatēts, bet to nevar parsēt. Piedodiet.",
LYRICS_TITLE_INVALID:		"Video nosaukums neatbilst «Mākslinieks - Sadaļa» modelis!",
RATING_LIKE:				"%pcent% — patīk",
RATING_NO_DATA:				"Vērtējums nav pieejams."
},
// മലയാളം (Malayalam)
// "ml": {
// },
// मराठी (Marathi (Marāṭhī))
// "mr": {
// },
// Bahasa Melayu (Malay)
"ms": {
PREFERENCES:				"Pilihan...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(Kosong)",
DOWNLOAD_EMPTY_TIP:			"Data untuk download tidak dijumpai",
DOWNLOAD_UNKNOWN_TIP:		"diketahui format video",
STEP_FRAME_FORWARD:			"Langkah satu frame ke depan",
SEEK_FORWARD:				"Cari maju",
SEEK_BACK:					"Cari kembali",
POPOUT_PLAYER:				"Pop keluar pemain video",
LOOP_DISABLE:				"Matikan pengulangan",
LOOP_ENABLE:				"Aktifkan pengulangan",
LOOP_SECTION_DISABLE:		"Matikan bahagian pengulangan",
LOOP_SECTION_ENABLE:		"Aktifkan bahagian pengulangan",
LOOP_MARK_START:			"Menandakan bahagian awal",
LOOP_MARK_END:				"Tanda bahagian akhir",
PREVIEW_START:				"Klik untuk memulakan preview video.",
PREVIEW_END:				"Klik untuk akhir preview video.",
LYRICS_BUTTON_HIDE:			"Maklum lirik",
LYRICS_BUTTON_SHOW:			"Papar lirik",
LYRICS_BUTTON_LOAD:			"Beban",
LYRICS_BUTTON_TRY:			"Cuba secara manual...",
LYRICS_LYRICS:				"Lirik",
LYRICS_LYRICS_FOR:			"Lirik untuk: %song",
LYRICS_TITLE_INFO:			"Masukkan artis dan tajuk lagu untuk mencari.",
LYRICS_TITLE_INFO_EX:		"Pisahkan dengan tanda hubung (seperti: Artis - Tajuk).",
LYRICS_SEARCH_START:		"Cari “%song”...",
LYRICS_SEARCH_NO_RESULT:	"Tidak ada hasil untuk “%song”.",
LYRICS_SEARCH_FOUND:		"Lirik dijumpai. Pembebanan...",
LYRICS_SEARCH_NOT_FOUND:	"Lirik yang tidak dijumpai dan tidak ada kombinasi yang lebih banyak untuk mencuba.",
LYRICS_PARSE_SEARCH:		"Parsing hasil carian...",
LYRICS_PARSE_LYRICS:		"Parsing lirik maklumat...",
LYRICS_PARSE_SUCCESS:		"Lirik berjaya dipecah.",
LYRICS_PARSE_ERROR:			"Lirik yang ditemui tetapi tidak dapat diurai. Maaf.",
LYRICS_TITLE_INVALID:		"Video judul tidak sesuai “Artis - Tajuk” pola!",
RATING_LIKE:				"%pcent% suka",
RATING_NO_DATA:				"Kedudukan tidak terdapat."
},
// Nederlands (Dutch)
//	Thanks to:
//		Robin ten Berge <robin_tenberge@hotmail.com>
//		Don van Weverwijk <Creadskel@gmail.com>
//		Alwyn Kik <alwyn_kik@hotmail.com>
//		J. Puik
"nl": {
PREFERENCES:				"Instellingen...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(leeg)",
DOWNLOAD_EMPTY_TIP:			"Data voor download niet gevonden",
DOWNLOAD_UNKNOWN_TIP:		"onbekende video-formaat", // new
STEP_FRAME_FORWARD:			"Stap een frame naar voren",
SEEK_FORWARD:				"Zoek verder",
SEEK_BACK:					"Zoek terug",
POPOUT_PLAYER:				"Pop out video-speler", // new
LOOP_DISABLE:				"Automatisch afspelen uitzetten",
LOOP_ENABLE:				"Automatisch afspelen aanzetten",
LOOP_SECTION_DISABLE:		"Geselecteerde lus uitzetten",
LOOP_SECTION_ENABLE:		"Geselecteerde lus aanzetten",
LOOP_MARK_START:			"Markeer als start sectie",
LOOP_MARK_END:				"Markeer als einde sectie",
PREVIEW_START:				"Klik om video preview te starten.", // new
PREVIEW_END:				"Klik om video preview te beëindigen.", // new
LYRICS_BUTTON_HIDE:			"Liedteksten verbergen",
LYRICS_BUTTON_SHOW:			"Liedteksten tonen",
LYRICS_BUTTON_LOAD:			"Laad",
LYRICS_BUTTON_TRY:			"Zelf invullen...",
LYRICS_LYRICS:				"Liedteksten",
LYRICS_LYRICS_FOR:			"Liedteksten voor: %song",
LYRICS_TITLE_INFO:			"Voer artiest en titelnaam van het nummer in om deze te zoeken.",
LYRICS_TITLE_INFO_EX:		"Gebruik streepje om artiest en titel te scheiden (bijv: Artiest - Titel).",
LYRICS_SEARCH_START:		"Zoekt naar “%song”...",
LYRICS_SEARCH_NO_RESULT:	"“%song” is niet gevonden.",
LYRICS_SEARCH_FOUND:		"Liedteksten gevonden. Een moment...",
LYRICS_SEARCH_NOT_FOUND:	"Liedteksten niet gevonden en geen combinaties meer om te proberen.",
LYRICS_PARSE_SEARCH:		"Zoekresultaten worden verwerkt...",
LYRICS_PARSE_LYRICS:		"Liedtekst data word verwerkt...",
LYRICS_PARSE_SUCCESS:		"Liedtekst succesvol verwerkt.",
LYRICS_PARSE_ERROR:			"Liedtekst zijn gevonden, maar kunnen niet verwerkt worden.",
LYRICS_TITLE_INVALID:		"Video titel komt niet overeen met “Artiest - Titel”.",
RATING_LIKE:				"%pcent% stemmen voor leuk", // new
RATING_NO_DATA:				"Cijfer niet beschikbaar." // new
},
// Norsk (Norwegian)
//	Thanks to:
//		Dennis Moe
//		Are Kristoffer Lamo <arelamo@studioare.net>
"no": {
PREFERENCES:				"Innstillinger...",
DOWNLOAD_VIDEO:				"Last ned video",
DOWNLOAD_EMPTY:				"(tomt)",
DOWNLOAD_EMPTY_TIP:			"Data for nedlasting eksisterer ikke",
DOWNLOAD_UNKNOWN_TIP:		"Ukjent videoformat",
STEP_FRAME_FORWARD:			"Gå en bilderute frem",
SEEK_FORWARD:				"Spol frem",
SEEK_BACK:					"Spol tilbake",
POPOUT_PLAYER:				"Vis bare video", // new
LOOP_DISABLE:				"Deaktiver repetering",
LOOP_ENABLE:				"Aktiver repetering",
LOOP_SECTION_DISABLE:		"Deaktiver seksjonsrepetering",
LOOP_SECTION_ENABLE:		"Aktiver seksjonsrepetering",
LOOP_MARK_START:			"Marker seksjonens start",
LOOP_MARK_END:				"Marker seksjonens slutt",
PREVIEW_START:				"Klikk for å starte video forhåndsvisning.", // new
PREVIEW_END:				"Klikk for å avslutte forhåndsvisning av video.", // new
LYRICS_BUTTON_HIDE:			"Gjem sangtekst",
LYRICS_BUTTON_SHOW:			"Vis sangtekst",
LYRICS_BUTTON_LOAD:			"Last sangtekst",
LYRICS_BUTTON_TRY:			"Velg sangtekst selv...",
LYRICS_LYRICS:				"Sangtekst",
LYRICS_LYRICS_FOR:			"Sangtekst til: %song",
LYRICS_TITLE_INFO:			"Skriv inn artist og tittel på sangen for å søke etter den.",
LYRICS_TITLE_INFO_EX:		"Separer med bindestrek (Som: Artist - Tittel).",
LYRICS_SEARCH_START:		"Søker etter «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Ingen resultater for «%song».",
LYRICS_SEARCH_FOUND:		"Sangtekst funnet. Laster...",
LYRICS_SEARCH_NOT_FOUND:	"Fant ikke sangtekst og ingen flere kombinasjoner å prøve",
LYRICS_PARSE_SEARCH:		"Analyserer søkeresultater...",
LYRICS_PARSE_LYRICS:		"Analyserer sangtekstinformasjon...",
LYRICS_PARSE_SUCCESS:		"Sangtekst fullstendig analysert.",
LYRICS_PARSE_ERROR:			"Sangtekst er funnet, men kan ikke bli analysert. Beklager.",
LYRICS_TITLE_INVALID:		"Videotittel stemmer ikke overens med «Artist - Tittel» mønsteret!",
RATING_LIKE:				"%pcent% liker", // new
RATING_NO_DATA:				"Video karakter ikke tilgjengelig." // new
},
// Polski (Polish)
//	Thanks to:
//		Kamil Wyrzykowski <k.wyrzykowski@gmail.com>
//		Maksymilian Lutek <maximusadw@gmail.com>
//		Galhali <galhali@o2.pl>
//		Daniel M <danielm86@wp.pl>
"pl": {
PREFERENCES:				"Ustawienia...",
DOWNLOAD_VIDEO:				"Pobierz plik wideo",
DOWNLOAD_EMPTY:				"(puste)",
DOWNLOAD_EMPTY_TIP:			"Nie odnaleziono danych do pobrania",
DOWNLOAD_UNKNOWN_TIP:		"nieznany format wideo", // new
STEP_FRAME_FORWARD:			"Przejdź o jedną klatkę do przodu",
SEEK_FORWARD:				"Przewiń do przodu",
SEEK_BACK:					"Przewiń do tyłu",
POPOUT_PLAYER:				"Pokaż tylko wideo", // new
LOOP_DISABLE:				"Wyłacz zapętlanie",
LOOP_ENABLE:				"Włącz zapętlanie",
LOOP_SECTION_DISABLE:		"Wyłącz zapętlanie sekcji",
LOOP_SECTION_ENABLE:		"Włącz zapętlanie sekcji",
LOOP_MARK_START:			"Zaznacz początek sekcji",
LOOP_MARK_END:				"Zaznacz koniec sekcji",
PREVIEW_START:				"Kliknij, aby uruchomić podgląd wideo.", // new
PREVIEW_END:				"Kliknij, aby zakończyć podgląd wideo.", // new
LYRICS_BUTTON_HIDE:			"Ukryj tekst utworu",
LYRICS_BUTTON_SHOW:			"Pokaż tekst utworu",
LYRICS_BUTTON_LOAD:			"Wczytaj",
LYRICS_BUTTON_TRY:			"Spróbuj ręcznie...",
LYRICS_LYRICS:				"Tekst utworu",
LYRICS_LYRICS_FOR:			"Tekst dla utworu: %song",
LYRICS_TITLE_INFO:			"Wpisz wykonawcę i tytuł piosenki w celu wyszukania",
LYRICS_TITLE_INFO_EX:		"Oddzielone myślnikiem (w taki sposób: Wykonawca - Tytuł).",
LYRICS_SEARCH_START:		"Wyszukiwanie „%song”...",
LYRICS_SEARCH_NO_RESULT:	"Brak wyników dla „%song”.",
LYRICS_SEARCH_FOUND:		"Tekst znaleziony. Wczytywanie...",
LYRICS_SEARCH_NOT_FOUND:	"Tekst nie został odnaleziony i nie istnieje więcej kombinacji do sprawdzenia.",
LYRICS_PARSE_SEARCH:		"Przetwarzanie wyników wyszukiwania...",
LYRICS_PARSE_LYRICS:		"Przetwarzanie danych tekstu...",
LYRICS_PARSE_SUCCESS:		"Tekst udało się przetworzyć.",
LYRICS_PARSE_ERROR:			"Tekst znaleziony ale nie może być przetworzony. Przepraszamy.",
LYRICS_TITLE_INVALID:		"Tytuł filmu nie pasuje do wzorca „Wykonawca - Tytuł”!",
RATING_LIKE:				"Głosy na tak: %pcent%", // new
RATING_NO_DATA:				"Ocena nie jest dostępny." // new
},
// Português Brasileiro (Brazilian Portuguese)
//	Thanks to:
//		Jose Renan <joseassis1993@gmail.com>
//		Romário Paiva
//		Lucas Rafael Barboza <webmaster@lucasrafael.com.br>
//		André Zanghelini
"pt_BR": {
PREFERENCES:				"Preferências...",
DOWNLOAD_VIDEO:				"Baixar vídeo",
DOWNLOAD_EMPTY:				"(vazio)",
DOWNLOAD_EMPTY_TIP:			"Não foi possível encontrar o vídeo para baixar",
DOWNLOAD_UNKNOWN_TIP:		"formato de vídeo desconhecido",
STEP_FRAME_FORWARD:			"Avançar um quadro",
SEEK_FORWARD:				"Avançar",
SEEK_BACK:					"Voltar",
POPOUT_PLAYER:				"Mostrar apenas o vídeo",
LOOP_DISABLE:				"Desativar repetição",
LOOP_ENABLE:				"Ativar repetição",
LOOP_SECTION_DISABLE:		"Desativar repetição de seção",
LOOP_SECTION_ENABLE:		"Ativar repetição de seção",
LOOP_MARK_START:			"Marcar início de seção",
LOOP_MARK_END:				"Marcar final de sação",
PREVIEW_START:				"Iniciar visualização do vídeo.",
PREVIEW_END:				"Parar visualização do vídeo.",
LYRICS_BUTTON_HIDE:			"Ocultar letras",
LYRICS_BUTTON_SHOW:			"Exibir letras",
LYRICS_BUTTON_LOAD:			"Pesquisar",
LYRICS_BUTTON_TRY:			"Pesquisar manualmente...",
LYRICS_LYRICS:				"Letra da música",
LYRICS_LYRICS_FOR:			"Letras da música para: %song",
LYRICS_TITLE_INFO:			"Insira o nome do artista e o título da música para procurar:",
LYRICS_TITLE_INFO_EX:		"Separar por hífen (como: Artista - Título).",
LYRICS_SEARCH_START:		"Procurando por “%song”...",
LYRICS_SEARCH_NO_RESULT:	"Nenhum resultado para “%song”.",
LYRICS_SEARCH_FOUND:		"Letra encontrada. Carregando...",
LYRICS_SEARCH_NOT_FOUND:	"Nenhuma letra foi encontrada e não há mais combinações para tentar.",
LYRICS_PARSE_SEARCH:		"Analizando resultados da busca...",
LYRICS_PARSE_LYRICS:		"Analizando dados da letra...",
LYRICS_PARSE_SUCCESS:		"Letra de música carregada com sucesso.",
LYRICS_PARSE_ERROR:			"Letra encontrada, porém não pôde ser analizada. Desculpe.",
LYRICS_TITLE_INVALID:		"Título do vídeo não corresponde “Artista - Título” exemplo!",
RATING_LIKE:				"%pcent% pessoa(s) gosta(m)",
RATING_NO_DATA:				"Avaliação não disponível."
},
// Português (European Portuguese)
//	Thanks to:
//		Miguel Clara <miguelmclara@gmail.com>
//		Pedro Magalhães <pedromagalhaes@gmx.com>
"pt_PT": {
PREFERENCES:				"Preferências...",
DOWNLOAD_VIDEO:				"Descarregar vídeo",
DOWNLOAD_EMPTY:				"(vazio)",
DOWNLOAD_EMPTY_TIP:			"Dados para descarga não encontrados",
DOWNLOAD_UNKNOWN_TIP:		"formato de vídeo desconhecido",
STEP_FRAME_FORWARD:			"Avançar uma frame",
SEEK_FORWARD:				"Pesquisar à frente",
SEEK_BACK:					"Pesquisar para trás",
POPOUT_PLAYER:				"Mostrar apenas o vídeo",
LOOP_DISABLE:				"Desactivar repetição",
LOOP_ENABLE:				"Activar repetição",
LOOP_SECTION_DISABLE:		"Desactivar repetição de selecção",
LOOP_SECTION_ENABLE:		"Desactivar repetição de selecção",
LOOP_MARK_START:			"Marcar início de selecção",
LOOP_MARK_END:				"Marcar fim de selecção",
PREVIEW_START:				"Clique para começar a visualização de vídeo.", // new
PREVIEW_END:				"Clique para final de visualização de vídeo.", // new
LYRICS_BUTTON_HIDE:			"Esconder letras de músicas",
LYRICS_BUTTON_SHOW:			"Mostrar letras de músicas",
LYRICS_BUTTON_LOAD:			"Carregar",
LYRICS_BUTTON_TRY:			"Tentar manualmente...",
LYRICS_LYRICS:				"Letras de músicas",
LYRICS_LYRICS_FOR:			"Letras para: %song",
LYRICS_TITLE_INFO:			"Insira um artista e título da canção para pesquisar.",
LYRICS_TITLE_INFO_EX:		"Separado com hífen (exemplo: Artista - Titulo).",
LYRICS_SEARCH_START:		"A pesquisar por «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Nenhum resultado encontrado «%song».",
LYRICS_SEARCH_FOUND:		"Letra encontrada, a carregar...",
LYRICS_SEARCH_NOT_FOUND:	"Não foram encontradas letras e não há mais combinações para tentar.",
LYRICS_PARSE_SEARCH:		"A analisar os resultados da pesquisa...",
LYRICS_PARSE_LYRICS:		"A analisar os dados da letra...",
LYRICS_PARSE_SUCCESS:		"Letra analisada com sucesso.",
LYRICS_PARSE_ERROR:			"A letra foi encontrada, mas não pode ser analisada. Lamentamos o incómodo.",
LYRICS_TITLE_INVALID:		"O título do vídeo não corresponde ao padrão «Artista - Titulo»!",
RATING_LIKE:				"%pcent% utilizadores que gostaram deste vídeo", // new
RATING_NO_DATA:				"Avaliação não disponível." // new
},
// Română (Romanian)
"ro": {
PREFERENCES:				"Preferinţe...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(gol)",
DOWNLOAD_EMPTY_TIP:			"Datele pentru download nu a fost găsit",
DOWNLOAD_UNKNOWN_TIP:		"necunoscut format video",
STEP_FRAME_FORWARD:			"Un cadru pas înainte",
SEEK_FORWARD:				"Căuta înainte",
SEEK_BACK:					"Căuta înapoi",
POPOUT_PLAYER:				"Afişare video numai",
LOOP_DISABLE:				"Dezactiva buclă",
LOOP_ENABLE:				"Permite buclă",
LOOP_SECTION_DISABLE:		"Dezactiva secţiune buclă",
LOOP_SECTION_ENABLE:		"Permite bucla secţiune",
LOOP_MARK_START:			"Marca secţiune începe",
LOOP_MARK_END:				"Marca sfârşitul secţiune",
PREVIEW_START:				"Click pentru a incepe previzualizare video.",
PREVIEW_END:				"Faceţi clic pentru a termina previzualizare video.",
LYRICS_BUTTON_HIDE:			"Ascunde versuri",
LYRICS_BUTTON_SHOW:			"Arată versuri",
LYRICS_BUTTON_LOAD:			"Sarcină",
LYRICS_BUTTON_TRY:			"Încercaţi manual...",
LYRICS_LYRICS:				"Versuri",
LYRICS_LYRICS_FOR:			"Versuri pentru: %song",
LYRICS_TITLE_INFO:			"Introduceţi artist şi titlul de cântec pentru a căuta.",
LYRICS_TITLE_INFO_EX:		"Separate prin cratimă (cum ar fi aşa: Artist - Titlul).",
LYRICS_SEARCH_START:		"Căutarea pentru „%song”...",
LYRICS_SEARCH_NO_RESULT:	"Nici un rezultat pentru „%song”.",
LYRICS_SEARCH_FOUND:		"Versuri găsit. Se incarca...",
LYRICS_SEARCH_NOT_FOUND:	"Versurile nu sunt găsite şi nu pentru a încerca mai multe combinaţii.",
LYRICS_PARSE_SEARCH:		"Parsarea rezultatele de căutare...",
LYRICS_PARSE_LYRICS:		"Versuri Parsarea de date...",
LYRICS_PARSE_SUCCESS:		"Versuri cu succes analizat.",
LYRICS_PARSE_ERROR:			"Versurile sunt găsite, dar nu pot fi analizate. Ne pare rau.",
LYRICS_TITLE_INVALID:		"Titlul video nu se potriveşte cu „Artist - titlul” model!",
RATING_LIKE:				"%pcent% au apreciat",
RATING_NO_DATA:				"Rating-ul nu este disponibil."
},
// Русский (Russian)
//	Thanks to:
//		Игорь Харитонов <nimrod07@rambler.ru>
//		Антон Шаповалов <333hronos@gmail.com>
//		Кирилл Климанов <lakaicheaker@gmail.com>
//		Тимур Давлетшин <Davletwin@gmail.com>
//		Маргарита Бабовникова <babovnikova@gmail.com>
"ru": {
PREFERENCES:				"Настройки...",
DOWNLOAD_VIDEO:				"Скачать видео",
DOWNLOAD_EMPTY:				"(пусто)",
DOWNLOAD_EMPTY_TIP:			"Файл для загрузки не найден",
DOWNLOAD_UNKNOWN_TIP:		"неизвестный формат видео", // new
STEP_FRAME_FORWARD:			"Вперед на один кадр",
SEEK_FORWARD:				"Искать вперед",
SEEK_BACK:					"Искать назад",
POPOUT_PLAYER:				"Показать только видео", // new
LOOP_DISABLE:				"Отключить повтор",
LOOP_ENABLE:				"Включить повтор",
LOOP_SECTION_DISABLE:		"Отключить повтор раздела",
LOOP_SECTION_ENABLE:		"Включить повтор раздела",
LOOP_MARK_START:			"Назначить начало раздела",
LOOP_MARK_END:				"Назначить конец раздела",
PREVIEW_START:				"Нажмите, чтобы начать просмотр видео.", // new
PREVIEW_END:				"Нажмите до конца предварительного просмотра видео.", // new
LYRICS_BUTTON_HIDE:			"Скрыть текст песен",
LYRICS_BUTTON_SHOW:			"Показать текст песен",
LYRICS_BUTTON_LOAD:			"Загрузить",
LYRICS_BUTTON_TRY:			"Повторить вручную...",
LYRICS_LYRICS:				"Текст песен",
LYRICS_LYRICS_FOR:			"Текст песен для: %song",
LYRICS_TITLE_INFO:			"Вставьте исполнителя и название песни для поиска.",
LYRICS_TITLE_INFO_EX:		"Отделить дефисом (например: Исполнитель - Название).",
LYRICS_SEARCH_START:		"Поиск для «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Нет результатов для «%song».",
LYRICS_SEARCH_FOUND:		"Текст песни найден. Идет загрузка...",
LYRICS_SEARCH_NOT_FOUND:	"Текст песни не найден, варианты для поиска отсутствуют.",
LYRICS_PARSE_SEARCH:		"Анализ результатов поиска...",
LYRICS_PARSE_LYRICS:		"Разбор данных текста...",
LYRICS_PARSE_SUCCESS:		"Текст песен успешно проанализирован.",
LYRICS_PARSE_ERROR:			"Текст песен были найден, но не может быть проанализирован. Извините.",
LYRICS_TITLE_INVALID:		"Название видео не соответствует шаблону «Исполнитель - Название»!",
RATING_LIKE:				"%pcent% понравилось", // new
RATING_NO_DATA:				"Рейтинг не доступны." // new
},
// Slovenský (Slovak)
//	Thanks to:
//		Michal Galan <michal.galan@post.sk>
//		Jaroslav Andrejovský <andrejovsky.jaro@gmail.com>
"sk": {
PREFERENCES:				"Nastavenia...",
DOWNLOAD_VIDEO:				"Stiahnuť video",
DOWNLOAD_EMPTY:				"(nedostupné)",
DOWNLOAD_EMPTY_TIP:			"Dáta na stiahnutie neboli nájdené",
DOWNLOAD_UNKNOWN_TIP:		"neznámy formát videa", // new
STEP_FRAME_FORWARD:			"Krok o jeden snímok vpred",
SEEK_FORWARD:				"Skok vpred",
SEEK_BACK:					"Skok späť",
POPOUT_PLAYER:				"Zobraziť iba video", // new
LOOP_DISABLE:				"Vypnúť opakovanie",
LOOP_ENABLE:				"Zapnúť opakovanie",
LOOP_SECTION_DISABLE:		"Vypnúť opakovanie výberu",
LOOP_SECTION_ENABLE:		"Zapnúť opakovanie výberu",
LOOP_MARK_START:			"Označiť začiatok výberu",
LOOP_MARK_END:				"Označiť koniec výberu",
PREVIEW_START:				"Kliknite na tlačidlo pre spustenie videa náhľadu.", // new
PREVIEW_END:				"Kliknite do konca náhľad videa.", // new
LYRICS_BUTTON_HIDE:			"Skryť text piesne",
LYRICS_BUTTON_SHOW:			"Zobraziť text piesne",
LYRICS_BUTTON_LOAD:			"Načítať text piesne",
LYRICS_BUTTON_TRY:			"Zadať názvy ručne...",
LYRICS_LYRICS:				"Texty piesne",
LYRICS_LYRICS_FOR:			"Text pre: %song",
LYRICS_TITLE_INFO:			"Napíšte meno umelca a názov piesne, ktorú chcete hľadať.",
LYRICS_TITLE_INFO_EX:		"Oddeľte pomlčkou (napríklad: Interpret - Názov piesne).",
LYRICS_SEARCH_START:		"Hľadanie pre „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Žiadne výsledky hľadania pre „%song“.",
LYRICS_SEARCH_FOUND:		"Text piesne nájdený. Načítava sa...",
LYRICS_SEARCH_NOT_FOUND:	"Boli vyskúšané všetky kombinácie, ale text nebol nájdený.",
LYRICS_PARSE_SEARCH:		"Spracovávanie výsledkov hľadania...",
LYRICS_PARSE_LYRICS:		"Spracovávanie textu piesne...",
LYRICS_PARSE_SUCCESS:		"Text piesne úspešne spracovaný.",
LYRICS_PARSE_ERROR:			"Text piesne bol nájdený, ale nie je ho možné spracovať. Ospravedlňujeme sa.",
LYRICS_TITLE_INVALID:		"Názov videa nezodpovedá vzoru „Interpret - Názov piesne“!",
RATING_LIKE:				"%pcent%-krát „Páči sa mi to“", // new
RATING_NO_DATA:				"Hodnotenie nie je k dispozícii." // new
},
// Slovenščina (Slovene)
//	Thanks to:
//		Vito Meznaric
"sl": {
PREFERENCES:				"Nastavitve...",
DOWNLOAD_VIDEO:				"Prenesi video",
DOWNLOAD_EMPTY:				"(prazno)",
DOWNLOAD_EMPTY_TIP:			"Ni podatkov za prenos",
DOWNLOAD_UNKNOWN_TIP:		"neznano video format", // new
STEP_FRAME_FORWARD:			"Ena sličica naprej",
SEEK_FORWARD:				"Prevrti naprej",
SEEK_BACK:					"Prevrti nazaj",
POPOUT_PLAYER:				"Prikaži samo video", // new
LOOP_DISABLE:				"Izklopi ponavljanje",
LOOP_ENABLE:				"Vklopi ponavljanje",
LOOP_SECTION_DISABLE:		"Izklopi ponavljanje predela",
LOOP_SECTION_ENABLE:		"Vklopi ponavljanje predela",
LOOP_MARK_START:			"Označi začetek predela",
LOOP_MARK_END:				"Označi konec predela",
PREVIEW_START:				"Kliknite za začetek predogled video.", // new
PREVIEW_END:				"Kliknite za konec predogled video.", // new
LYRICS_BUTTON_HIDE:			"Skri besedilo",
LYRICS_BUTTON_SHOW:			"Pokaži besedilo",
LYRICS_BUTTON_LOAD:			"Naloži",
LYRICS_BUTTON_TRY:			"Poskusi ročno...",
LYRICS_LYRICS:				"Besedilo",
LYRICS_LYRICS_FOR:			"Besedilo za: %song",
LYRICS_TITLE_INFO:			"Vstavi izvajalca in naslov pesmi za iskanje.",
LYRICS_TITLE_INFO_EX:		"Deli z pomišlajem (Naprimer: Izvajalec - Naslov).",
LYRICS_SEARCH_START:		"Iščem „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Ni rezultatov za „%song“.",
LYRICS_SEARCH_FOUND:		"Besedilo najdeno. Nalagam...",
LYRICS_SEARCH_NOT_FOUND:	"Besedilo ni najdeno in ni več kombinacij za poskusit.",
LYRICS_PARSE_SEARCH:		"Obdelujem rezultate iskanja...",
LYRICS_PARSE_LYRICS:		"Obdelujem rezultate besedila...",
LYRICS_PARSE_SUCCESS:		"Besedilo je bilo uspešno obdelano.",
LYRICS_PARSE_ERROR:			"Besedilo je najdeno vendar ne more biti obdelano. Oprostite.",
LYRICS_TITLE_INVALID:		"Naslov videa se ne ujema z „Izvajalec - Naslov“ vzorcem!",
RATING_LIKE:				"%pcent% glasov „Všeč mi je“", // new
RATING_NO_DATA:				"Ocena ni na voljo." // new
},
// Српски (Serbian)
//	Thanks to: me :), Дарко Пантић
"sr": {
PREFERENCES:				"Подешавања...",
DOWNLOAD_VIDEO:				"Преузмите видео запис",
DOWNLOAD_EMPTY:				"(празно)",
DOWNLOAD_EMPTY_TIP:			"Подаци за преузимање нису пронађени",
DOWNLOAD_UNKNOWN_TIP:		"непознат формат видео записа",
STEP_FRAME_FORWARD:			"Један фрејм напред",
SEEK_FORWARD:				"Скочи напред",
SEEK_BACK:					"Скочи уназад",
POPOUT_PLAYER:				"Прикажи само видео запис",
LOOP_DISABLE:				"Искључи понављање",
LOOP_ENABLE:				"Укључи понављање",
LOOP_SECTION_DISABLE:		"Искључи понављање дела видео записа",
LOOP_SECTION_ENABLE:		"Укључи понављање дела видео записа",
LOOP_MARK_START:			"Обележи почетак понављања",
LOOP_MARK_END:				"Обележи крај понављања",
PREVIEW_START:				"Кликните да бисте започели преглед видео записа",
PREVIEW_END:				"Кликните да бисте окончали преглед видео записа",
LYRICS_BUTTON_HIDE:			"Сакриј текст песме",
LYRICS_BUTTON_SHOW:			"Прикажи текст песме",
LYRICS_BUTTON_LOAD:			"Учитај",
LYRICS_BUTTON_TRY:			"Покушајте ручно...",
LYRICS_LYRICS:				"Текст песме",
LYRICS_LYRICS_FOR:			"Текст за песму: %song",
LYRICS_TITLE_INFO:			"Унесите име извођача и назив песме за претрагу.",
LYRICS_TITLE_INFO_EX:		"Одвојите их цртицом (нпр.: „Извођач - Назив песме“).",
LYRICS_SEARCH_START:		"У потрази за „%song“...",
LYRICS_SEARCH_NO_RESULT:	"Нема резултата за „%song“.",
LYRICS_SEARCH_FOUND:		"Текст песме је пронађен. Учитавање...",
LYRICS_SEARCH_NOT_FOUND:	"Текст песме није пронађен и нема више могућих комбинација.",
LYRICS_PARSE_SEARCH:		"Анализа резултата претраге...",
LYRICS_PARSE_LYRICS:		"Анализа текста...",
LYRICS_PARSE_SUCCESS:		"Текст песме је успешно анализиран.",
LYRICS_PARSE_ERROR:			"Текст песме је пронађен, али га је немогуће изанализирати. Извините због тога.",
LYRICS_TITLE_INVALID:		"Име видео записа не одговара шаблону „Извођач - Назив песме“!",
RATING_LIKE:				"Свиђа ми се: %pcent%",
RATING_NO_DATA:				"Оцена видео записа није доступна."
},
// Svenska (Swedish)
"sv": {
PREFERENCES:				"Inställningar...",
DOWNLOAD_VIDEO:				"Ladda ner video",
DOWNLOAD_EMPTY:				"(tom)",
DOWNLOAD_EMPTY_TIP:			"Data för nedladdning hittades inte",
DOWNLOAD_UNKNOWN_TIP:		"okänd videoformat",
STEP_FRAME_FORWARD:			"Steg en bildruta framåt",
SEEK_FORWARD:				"Söka framåt",
SEEK_BACK:					"Söka bakåt",
POPOUT_PLAYER:				"Visa endast video",
LOOP_DISABLE:				"Inaktivera slinga",
LOOP_ENABLE:				"Möjliggöra slinga",
LOOP_SECTION_DISABLE:		"Inaktivera avsnitt slinga",
LOOP_SECTION_ENABLE:		"Möjliggöra avsnitt slinga",
LOOP_MARK_START:			"Märke avsnitt start",
LOOP_MARK_END:				"Markera avsnittet slut",
PREVIEW_START:				"Klicka för att starta video-förhandsvisning.",
PREVIEW_END:				"Klicka för att avsluta video-förhandsgranskning.",
LYRICS_BUTTON_HIDE:			"Dölja texten",
LYRICS_BUTTON_SHOW:			"Visa texten",
LYRICS_BUTTON_LOAD:			"Belastning",
LYRICS_BUTTON_TRY:			"Försöka att manuellt...",
LYRICS_LYRICS:				"Texten",
LYRICS_LYRICS_FOR:			"Texten till: %song",
LYRICS_TITLE_INFO:			"Sätt artist och titel sång för att söka efter.",
LYRICS_TITLE_INFO_EX:		"Separat av bindestreck (så här: Artist - Titel).",
LYRICS_SEARCH_START:		"Letar efter ”%song”...",
LYRICS_SEARCH_NO_RESULT:	"Inga resultat för ”%song”.",
LYRICS_SEARCH_FOUND:		"Texten found. Laddar...",
LYRICS_SEARCH_NOT_FOUND:	"Texterna är inte hittats och ingen fler kombinationer att prova.",
LYRICS_PARSE_SEARCH:		"Parsning sökresultat...",
LYRICS_PARSE_LYRICS:		"Parsning texten data...",
LYRICS_PARSE_SUCCESS:		"Texten framgångsrikt analyserad.",
LYRICS_PARSE_ERROR:			"Texten finns men kan inte tolkas. Tyvärr.",
LYRICS_TITLE_INVALID:		"Videotitel matchar inte ”Artist - Titel” mönstret!",
RATING_LIKE:				"%pcent% gillar",
RATING_NO_DATA:				"Betyg saknas."
},
// Kiswahili (Swahili)
"sw": {
PREFERENCES:				"Upendeleo...",
DOWNLOAD_VIDEO:				"Shusha video",
DOWNLOAD_EMPTY:				"(tupu)",
DOWNLOAD_EMPTY_TIP:			"Takwimu kwa shusha halikupatikana",
DOWNLOAD_UNKNOWN_TIP:		"haijulikani video format",
STEP_FRAME_FORWARD:			"Hatua moja mbele frame",
SEEK_FORWARD:				"Kutafuta mbele",
SEEK_BACK:					"Kutafuta nyuma",
POPOUT_PLAYER:				"Onyesha video tu",
LOOP_DISABLE:				"Disable kitanzi",
LOOP_ENABLE:				"Kuwawezesha kitanzi",
LOOP_SECTION_DISABLE:		"Disable sehemu ya kitanzi",
LOOP_SECTION_ENABLE:		"Kuwawezesha sehemu ya kitanzi",
LOOP_MARK_START:			"Alama sehemu ya kuanza",
LOOP_MARK_END:				"Alama sehemu ya mwisho",
PREVIEW_START:				"Click kuanza hakikisho video.",
PREVIEW_END:				"Click mwisho hakikisho video.",
LYRICS_BUTTON_HIDE:			"Kujificha nakala ya wimbo",
LYRICS_BUTTON_SHOW:			"Kuonyesha nakala ya wimbo",
LYRICS_BUTTON_LOAD:			"Mzigo",
LYRICS_BUTTON_TRY:			"Kujaribu manually...",
LYRICS_LYRICS:				"Nakala ya wimbo",
LYRICS_LYRICS_FOR:			"Nakala ya wimbo: %song",
LYRICS_TITLE_INFO:			"Insert msanii na jina la wimbo wa kutafuta.",
LYRICS_TITLE_INFO_EX:		"Tofauti na hyphen (kama hivyo: Msanii - Title).",
LYRICS_SEARCH_START:		"Kwa ajili ya kutafuta “%song”...",
LYRICS_SEARCH_NO_RESULT:	"Hakuna matokeo kwa “%song”.",
LYRICS_SEARCH_FOUND:		"Nakala ya wimbo kupatikana. Upakiaji...",
LYRICS_SEARCH_NOT_FOUND:	"Nakala ya wimbo si kupatikana na hakuna michanganyiko zaidi kwa kujaribu.",
LYRICS_PARSE_SEARCH:		"Hazrat matokeo...",
LYRICS_PARSE_LYRICS:		"Hazrat lyrics data...",
LYRICS_PARSE_SUCCESS:		"Nakala ya wimbo mafanikio hazrat.",
LYRICS_PARSE_ERROR:			"Nakala ya wimbo ni kupatikana lakini hawezi kuwa hazrat. Msamaha.",
LYRICS_TITLE_INVALID:		"Video cheo haina mechi “Msanii - Title” mfano!",
RATING_LIKE:				"%pcent% waliipenda",
RATING_NO_DATA:				"Rating hazipatikani."
},
// தமிழ் (Tamil)
"ta": {
PREFERENCES:				"விருப்பங்கள்...",
DOWNLOAD_VIDEO:				"வீடியோ பதிவிறக்க",
DOWNLOAD_EMPTY:				"(வெற்று)",
DOWNLOAD_EMPTY_TIP:			"பதிவிறக்க தரவு இல்லை",
DOWNLOAD_UNKNOWN_TIP:		"தெரியாத வீடியோ வடிவமைப்பு",
STEP_FRAME_FORWARD:			"முன்னோக்கி ஒரு சட்டகம் தள்ளு",
SEEK_FORWARD:				"முன்னோக்கி தேடுங்கள்",
SEEK_BACK:					"திரும்ப பெற",
POPOUT_PLAYER:				"வீடியோ பிளேயர் வெளிவந்துவிடும்",
LOOP_DISABLE:				"கண்ணி முடக்கு",
LOOP_ENABLE:				"கண்ணி செயல்படுத்த",
LOOP_SECTION_DISABLE:		"பகுதியில் கண்ணி முடக்கு",
LOOP_SECTION_ENABLE:		"பகுதியில் கண்ணி செயல்படுத்த",
LOOP_MARK_START:			"மார்க் பிரிவு தொடக்க",
LOOP_MARK_END:				"மார்க் பிரிவில் இறுதி",
PREVIEW_START:				"வீடியோ முன்னோட்ட தொடங்க கிளிக் செய்யவும்.",
PREVIEW_END:				"வீடியோ முன்னோட்ட முடிக்க என்பதை கிளிக் செய்யவும்.",
LYRICS_BUTTON_HIDE:			"பாடல் மறை",
LYRICS_BUTTON_SHOW:			"பாடல் காட்டு",
LYRICS_BUTTON_LOAD:			"சுமை",
LYRICS_BUTTON_TRY:			"கைமுறையாக முயற்சி...",
LYRICS_LYRICS:				"பாடல்",
LYRICS_LYRICS_FOR:			"பாடல்: %song",
LYRICS_TITLE_INFO:			"கலைஞர் மற்றும் தேட பாடல் தலைப்பை சேர்க்க.",
LYRICS_TITLE_INFO_EX:		"ஹைபன் (போல: தலைப்பு - கலைஞர்) தனி.",
LYRICS_SEARCH_START:		"\"%song\" தேடுகிறது...",
LYRICS_SEARCH_NO_RESULT:	"\"%song\" முடிவுகள் இல்லை.",
LYRICS_SEARCH_FOUND:		"பாடல் காணப்படுகிறது. ஏறுகிறது...",
LYRICS_SEARCH_NOT_FOUND:	"பாடல் கிடைக்காத மேலும் சேர்க்கைகள் முயற்சி.",
LYRICS_PARSE_SEARCH:		"தேடல் முடிவுகளை பாகுபடுத்தல்...",
LYRICS_PARSE_LYRICS:		"பாடல் தரவு பாகுபடுத்தல்...",
LYRICS_PARSE_SUCCESS:		"பாடல் வெற்றிகரமாக அலச.",
LYRICS_PARSE_ERROR:			"பாடல் வரிகள் காணப்படுகின்றன ஆனால் அலச முடியாது. மன்னிக்கவும்.",
LYRICS_TITLE_INVALID:		"வீடியோ தலைப்பு \"கலைஞர் - தலைப்பு\" பொருந்தவில்லை பாணி!",
RATING_LIKE:				"%pcent% போன்ற",
RATING_NO_DATA:				"மதிப்பீடு இல்லை."
},
// తెలుగు (Telugu)
// "te": {
// },
// ภาษาไทย (Thai)
"th": {
PREFERENCES:				"...การตั้งค่า",
DOWNLOAD_VIDEO:				"วิดีโอดาวน์โหลด",
DOWNLOAD_EMPTY:				"(ไม่มี)",
DOWNLOAD_EMPTY_TIP:			"ข้อมูลสำหรับการดาวน์โหลดไม่พบ",
DOWNLOAD_UNKNOWN_TIP:		"รูปแบบวิดีโอที่ไม่รู้จัก",
STEP_FRAME_FORWARD:			"ขั้นตอนทีละเฟรมไปข้างหน้า",
SEEK_FORWARD:				"ขอไปข้างหน้า",
SEEK_BACK:					"ขอกลับ",
POPOUT_PLAYER:				"แสดงวิดีโอเท่านั้น",
LOOP_DISABLE:				"ลูปปิดการใช้งาน",
LOOP_ENABLE:				"เปิดใช้งานลูป",
LOOP_SECTION_DISABLE:		"ส่วนลูปปิดการใช้งาน",
LOOP_SECTION_ENABLE:		"เปิดใช้งานส่วนลูป",
LOOP_MARK_START:			"เริ่มต้นส่วนเครื่องหมาย",
LOOP_MARK_END:				"ส่วนท้ายทำเครื่องหมาย",
PREVIEW_START:				"คลิกเพื่อเริ่มการแสดงตัวอย่างวิดีโอ",
PREVIEW_END:				"คลิกเพื่อสิ้นสุดการแสดงตัวอย่างวิดีโอ",
LYRICS_BUTTON_HIDE:			"ซ่อนเนื้อเพลง",
LYRICS_BUTTON_SHOW:			"แสดงเนื้อเพลง",
LYRICS_BUTTON_LOAD:			"ภาระ",
LYRICS_BUTTON_TRY:			"...ลองด้วยตนเอง",
LYRICS_LYRICS:				"เนื้อเพลง",
LYRICS_LYRICS_FOR:			"เนื้อเพลง: %song",
LYRICS_TITLE_INFO:			"แทรกศิลปินและชื่อของเพลงที่จะค้นหา",
LYRICS_TITLE_INFO_EX:		"แยกตามยัติภังค์ (เช่นเพื่อ : ศิลปิน - ชื่อเรื่อง)",
LYRICS_SEARCH_START:		"ค้นหา “%song”...",
LYRICS_SEARCH_NO_RESULT:	"ไม่มีผลลัพธ์สำหรับ “%song”.",
LYRICS_SEARCH_FOUND:		"พบนักร้อง การโหลด...",
LYRICS_SEARCH_NOT_FOUND:	"เนื้อเพลงไม่พบและไม่มีการผสมมากขึ้นในการพยายาม",
LYRICS_PARSE_SEARCH:		"แจงผลการค้นหา...",
LYRICS_PARSE_LYRICS:		"การแยกวิเคราะห์ข้อมูลเนื้อเพลง...",
LYRICS_PARSE_SUCCESS:		"แจงนักร้องได้สำเร็จ",
LYRICS_PARSE_ERROR:			"เนื้อเพลงจะพบ แต่ไม่สามารถแยกวิเคราะห์ ขอโทษ",
LYRICS_TITLE_INVALID:		"ชื่อวิดีโอไม่ตรงกับ“ศิลปิน - ชื่อเพลง”ลาย!",
RATING_LIKE:				"ชอบ %pcent% คน",
RATING_NO_DATA:				"คะแนนไม่สามารถใช้ได้"
},
// Tagalog (Tagalog; Filipino)
"tl": {
PREFERENCES:				"Mga kagustuhan...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(wala)",
DOWNLOAD_EMPTY_TIP:			"Data para sa download hindi natagpuan",
DOWNLOAD_UNKNOWN_TIP:		"hindi kilalang video format",
STEP_FRAME_FORWARD:			"Hakbang isa frame pasulong",
SEEK_FORWARD:				"Humingi ng pasulong",
SEEK_BACK:					"Humingi ng likod",
POPOUT_PLAYER:				"Ipakita ang video lamang",
LOOP_DISABLE:				"Huwag paganahin loop",
LOOP_ENABLE:				"Paganahin loop",
LOOP_SECTION_DISABLE:		"Hindi paganahin ang seksyon loop",
LOOP_SECTION_ENABLE:		"Paganahin ang seksyon loop",
LOOP_MARK_START:			"Markahan seksyon simulan",
LOOP_MARK_END:				"Markahan seksyon katapusan",
PREVIEW_START:				"I-click upang simulan ang video preview.",
PREVIEW_END:				"I-click upang tapusin ang video preview.",
LYRICS_BUTTON_HIDE:			"Itago teksto",
LYRICS_BUTTON_SHOW:			"Ipakita teksto",
LYRICS_BUTTON_LOAD:			"Magkarga",
LYRICS_BUTTON_TRY:			"Subukan manually...",
LYRICS_LYRICS:				"Teksto",
LYRICS_LYRICS_FOR:			"Teksto para sa: %song",
LYRICS_TITLE_INFO:			"Magsingit ng artist at title ng kanta sa paghahanap para sa.",
LYRICS_TITLE_INFO_EX:		"Hiwalay na sa pamamagitan ng gitling (tulad ng sa gayon: Artist - Title).",
LYRICS_SEARCH_START:		"Naghahanap para sa “%song”...",
LYRICS_SEARCH_NO_RESULT:	"Walang mga resulta para sa “%song”.",
LYRICS_SEARCH_FOUND:		"Teksto natagpuan. Pagkarga...",
LYRICS_SEARCH_NOT_FOUND:	"Teksto ay hindi natagpuan at walang higit pang mga kumbinasyon na subukan.",
LYRICS_PARSE_SEARCH:		"Pag-parse ng mga resulta ng paghahanap...",
LYRICS_PARSE_LYRICS:		"Pag-parse ng teksto ng data...",
LYRICS_PARSE_SUCCESS:		"Teksto matagumpay parse.",
LYRICS_PARSE_ERROR:			"Teksto ay natagpuan ngunit hindi maaaring ma-parse. Sorry.",
LYRICS_TITLE_INVALID:		"Video title ay hindi tumutugma sa “Artist - Title” pattern!",
RATING_LIKE:				"%pcent% (na) gusto",
RATING_NO_DATA:				"Rating hindi magagamit."
},
// Türkçe (Turkish)
//	Thanks to:
//		Murat SO <so.murat@hotmail.com>
"tr": {
PREFERENCES:				"Tercihler...",
DOWNLOAD_VIDEO:				"Videoyu indir",
DOWNLOAD_EMPTY:				"(boş)",
DOWNLOAD_EMPTY_TIP:			"İndirmek için bilgi bulunamadı",
DOWNLOAD_UNKNOWN_TIP:		"bilinmeyen video formatı", // new
STEP_FRAME_FORWARD:			"Bir kare ileri git",
SEEK_FORWARD:				"Geriye git",
SEEK_BACK:					"İleri git",
POPOUT_PLAYER:				"Video yalnızca göster", // new
LOOP_DISABLE:				"Videoyu tekrarla",
LOOP_ENABLE:				"Video tekrarlamayı durdur",
LOOP_SECTION_DISABLE:		"Bölümü tekrarlamayı durdur",
LOOP_SECTION_ENABLE:		"Bölümü tekrarla",
LOOP_MARK_START:			"Bölüm başını işaretle",
LOOP_MARK_END:				"Bölüm sonunu işaretle",
PREVIEW_START:				"Video önizleme başlatmak için tıklayın.", // new
PREVIEW_END:				"Video önizleme bitirmek için tıklayın.", // new
LYRICS_BUTTON_HIDE:			"Şarkı sözlerini sakla",
LYRICS_BUTTON_SHOW:			"Şarkı sözlerini göster",
LYRICS_BUTTON_LOAD:			"Yükle",
LYRICS_BUTTON_TRY:			"Kendiniz deneyin...",
LYRICS_LYRICS:				"Şarkı sözleri",
LYRICS_LYRICS_FOR:			"%song için şarkı sözleri.",
LYRICS_TITLE_INFO:			"Aramak için şarkıcı ve şarkı adını giriniz.",
LYRICS_TITLE_INFO_EX:		"Tire ile ayırınız (örneğin: Şarkıcı - Şarkı).",
LYRICS_SEARCH_START:		"«%song» için şarkı sözü aranıyor.",
LYRICS_SEARCH_NO_RESULT:	"«%song» için şarkı sözü bulunamadı.",
LYRICS_SEARCH_FOUND:		"Sözler bulundu. Yükleniyor...",
LYRICS_SEARCH_NOT_FOUND:	"Sözler bulunamadı ve denemek için kombinasyon kalmadı.",
LYRICS_PARSE_SEARCH:		"Arama sonuçları getiriliyor...",
LYRICS_PARSE_LYRICS:		"Söz bilgileri getiriliyor...",
LYRICS_PARSE_SUCCESS:		"Sözler başarıyla getirildi.",
LYRICS_PARSE_ERROR:			"Sözler bulundu ama getirilimiyor. Özür dileriz.",
LYRICS_TITLE_INVALID:		"Videonun adı «Şarkıcı - Şarkı» örneğine uymuyor!",
RATING_LIKE:				"%pcent% gibi", // new
RATING_NO_DATA:				"Değerlendirme kullanılabilir değil." // new
},
// Українська (Ukrainian)
//	Thanks to:
//		Петро Віжевський
//		Evol G.
"uk": {
PREFERENCES:				"Налаштування...",
DOWNLOAD_VIDEO:				"Завантажити відео",
DOWNLOAD_EMPTY:				"(пусто)",
DOWNLOAD_EMPTY_TIP:			"Даних для завантаження не знайдено",
DOWNLOAD_UNKNOWN_TIP:		"невідомий формат відео", // new
STEP_FRAME_FORWARD:			"Один кадр вперед",
SEEK_FORWARD:				"Переміститися вперед",
SEEK_BACK:					"Переміститися назад",
POPOUT_PLAYER:				"Показати тільки відео", // new
LOOP_DISABLE:				"Вимкнути зациклення",
LOOP_ENABLE:				"Увімкнути зациклення",
LOOP_SECTION_DISABLE:		"Вимкнути зациклення уривку",
LOOP_SECTION_ENABLE:		"Увімкнути зациклення уривку",
LOOP_MARK_START:			"Позначити початок уривку",
LOOP_MARK_END:				"Позначити кінець уривку",
PREVIEW_START:				"Натисніть, щоб почати перегляд відео.", // new
PREVIEW_END:				"Натисніть до кінця попереднього перегляду відео.", // new
LYRICS_BUTTON_HIDE:			"Приховати текст",
LYRICS_BUTTON_SHOW:			"Показати текст",
LYRICS_BUTTON_LOAD:			"Завантажити",
LYRICS_BUTTON_TRY:			"Спробувати вручну...",
LYRICS_LYRICS:				"Текст",
LYRICS_LYRICS_FOR:			"Текст для: %song",
LYRICS_TITLE_INFO:			"Введіть виконавця та назву пісні для пошуку.",
LYRICS_TITLE_INFO_EX:		"Розділяти дефісом(наприклад: Виконавець - Назва).",
LYRICS_SEARCH_START:		"Пошук для «%song»...",
LYRICS_SEARCH_NO_RESULT:	"Немає результатів для «%song».",
LYRICS_SEARCH_FOUND:		"Текст знайдено. Завантаження...",
LYRICS_SEARCH_NOT_FOUND:	"Текст не знайдено, варіанти для пошуку відсутні",
LYRICS_PARSE_SEARCH:		"Аналіз результатів пошуку...",
LYRICS_PARSE_LYRICS:		"Аналіз даних тексту...",
LYRICS_PARSE_SUCCESS:		"Текст проаналізовано корректно.",
LYRICS_PARSE_ERROR:			"Текст знайдений, але не може бути проаналізований. Звиняйте.",
LYRICS_TITLE_INVALID:		"Назва відео не	відповідає шаблону «Виконавець - Назва»!",
RATING_LIKE:				"Сподобалося: %pcent%", // new
RATING_NO_DATA:				"Рейтинг не доступні." // new
},
// اردو (Urdu)
"ur": {
PREFERENCES:				"کی ترجیحات...",
DOWNLOAD_VIDEO:				"ڈاؤن لوڈ ، اتارنا ویڈیو",
DOWNLOAD_EMPTY:				"(خالی)",
DOWNLOAD_EMPTY_TIP:			"ڈاؤن لوڈ ، اتارنا لئے دستیاب معلومات نہیں مل سکا",
DOWNLOAD_UNKNOWN_TIP:		"نامعلوم ویڈیو فارمیٹ",
STEP_FRAME_FORWARD:			"ایک فریم آگے مرحلہ",
SEEK_FORWARD:				"آگے طلب کرو",
SEEK_BACK:					"واپس طلب کرو",
POPOUT_PLAYER:				"ویڈیو کھلاڑی پاپ",
LOOP_DISABLE:				"لوپ کو غیر فعال کریں",
LOOP_ENABLE:				"لوپ کو فعال کریں",
LOOP_SECTION_DISABLE:		"سیکشن لوپ کو غیر فعال",
LOOP_SECTION_ENABLE:		"سیکشن لوپ کو چالو کریں",
LOOP_MARK_START:			"کو بطور “خواندہ” نشان زد کریں سیکشن شروع",
LOOP_MARK_END:				"کو بطور “خواندہ” نشان زد کریں سیکشن آخر",
PREVIEW_START:				"ویڈیو پیش نظارہ شروع کرنے کے لئے یہاں دبائیں.",
PREVIEW_END:				"ویڈیو پیش نظارہ کو ختم کرنے کے لئے یہاں دبائیں.",
LYRICS_BUTTON_HIDE:			"دھن چھپائیں",
LYRICS_BUTTON_SHOW:			"دکھائیں کی دھن",
LYRICS_BUTTON_LOAD:			"لوڈ کریں",
LYRICS_BUTTON_TRY:			"دستی طور پر کرنے کی کوشش کریں...",
LYRICS_LYRICS:				"کی دھن",
LYRICS_LYRICS_FOR:			"کے لئے کی دھن: %song",
LYRICS_TITLE_INFO:			"آرٹسٹ اور تلاش کرنے کے لئے گیت کا عنوان ڈالیں.",
LYRICS_TITLE_INFO_EX:		"ہائفن کی طرف سے الگ الگ (تو اس طرح کہ : آرٹسٹ - عنوان).",
LYRICS_SEARCH_START:		"کی تلاش میں “%song”...",
LYRICS_SEARCH_NO_RESULT:	"کے لئے کوئی نتائج نہیں “%song”.",
LYRICS_SEARCH_FOUND:		"دھن مل گیا. لوڈ کیا جا رہا ہے...",
LYRICS_SEARCH_NOT_FOUND:	"کی دھن نہیں مل رہے ہیں اور کوئی زیادہ کے مجموعے کی کوشش کریں.",
LYRICS_PARSE_SEARCH:		"تلاش کے نتائج تصریف میں کیا جا رہا ہے...",
LYRICS_PARSE_LYRICS:		"دھن کے اعداد و شمار کی تصریف میں کیا جا رہا ہے...",
LYRICS_PARSE_SUCCESS:		"دھن کامیابی تجزیہ.",
LYRICS_PARSE_ERROR:			"کی دھن پایا ہے لیکن تجزیہ نہیں کیا جا سکتا ہیں. معاف کیجئے گا.",
LYRICS_TITLE_INVALID:		"“-- عنوان \ کلاکار” کی پیٹرن ویڈیو عنوان \ میل نہیں کھاتا ہے!",
RATING_LIKE:				"%pcent% پسند کرتا ہے",
RATING_NO_DATA:				"دستیاب نہیں کی درجہ بندی."
},
// Tiếng Việt (Vietnamese)
"vi": {
PREFERENCES:				"Ưu đãi...",
DOWNLOAD_VIDEO:				"Download video",
DOWNLOAD_EMPTY:				"(hết)",
DOWNLOAD_EMPTY_TIP:			"Dữ liệu để tải về không được tìm thấy",
DOWNLOAD_UNKNOWN_TIP:		"không rõ định dạng video",
STEP_FRAME_FORWARD:			"Bước một khung phía trước",
SEEK_FORWARD:				"Tìm kiếm sự chuyển tiếp",
SEEK_BACK:					"Tìm kiếm sự trở lại",
POPOUT_PLAYER:				"Hiển thị video chỉ",
LOOP_DISABLE:				"Vô hiệu hóa vòng lặp",
LOOP_ENABLE:				"Cho phép lặp",
LOOP_SECTION_DISABLE:		"Vô hiệu hóa phần vòng lặp",
LOOP_SECTION_ENABLE:		"Phần cho phép vòng lặp",
LOOP_MARK_START:			"Phần đánh dấu bắt đầu",
LOOP_MARK_END:				"Phần đánh dấu kết thúc",
PREVIEW_START:				"Nhấp vào để bắt đầu xem trước video.",
PREVIEW_END:				"Nhấp vào để kết thúc xem trước video.",
LYRICS_BUTTON_HIDE:			"Ẩn lời bài hát",
LYRICS_BUTTON_SHOW:			"Hiển thị lời bài hát",
LYRICS_BUTTON_LOAD:			"Tải",
LYRICS_BUTTON_TRY:			"Thử bằng tay...",
LYRICS_LYRICS:				"Lời bài hát",
LYRICS_LYRICS_FOR:			"Lời cho: %song",
LYRICS_TITLE_INFO:			"Chèn nghệ sĩ và Tiêu đề của bài hát để tìm kiếm.",
LYRICS_TITLE_INFO_EX:		"Riêng biệt bằng dấu gạch nối (như thế này: Nghệ sĩ - Tiêu đề).",
LYRICS_SEARCH_START:		"Tìm kiếm “%song”...",
LYRICS_SEARCH_NO_RESULT:	"Không có kết quả cho “%song”.",
LYRICS_SEARCH_FOUND:		"Lời bài hát được tìm thấy. Tải...",
LYRICS_SEARCH_NOT_FOUND:	"Lời bài hát không được tìm thấy và không có sự kết hợp nhiều hơn để thử.",
LYRICS_PARSE_SEARCH:		"Phân tích kết quả tìm kiếm...",
LYRICS_PARSE_LYRICS:		"Phân tích lời bài hát dữ liệu...",
LYRICS_PARSE_SUCCESS:		"Lời phân tích thành công.",
LYRICS_PARSE_ERROR:			"Lời bài hát được tìm thấy nhưng không thể được phân tích. Xin lôi.",
LYRICS_TITLE_INVALID:		"Video Tiêu đề không phù hợp “Nghệ sĩ - Tiêu đề” mô hình!",
RATING_LIKE:				"%pcent% người thích",
RATING_NO_DATA:				"Đánh giá không có."
},
// 中文 (简体) (Simplified Chinese)
"zh_CN": {
PREFERENCES:				"喜好...",
DOWNLOAD_VIDEO:				"下载视频",
DOWNLOAD_EMPTY:				"（空）",
DOWNLOAD_EMPTY_TIP:			"下载数据未找到",
DOWNLOAD_UNKNOWN_TIP:		"未知的视频格式",
STEP_FRAME_FORWARD:			"一步一帧​​前进",
SEEK_FORWARD:				"快进",
SEEK_BACK:					"寻找回来",
POPOUT_PLAYER:				"只显示视频",
LOOP_DISABLE:				"禁用循环",
LOOP_ENABLE:				"启用循环",
LOOP_SECTION_DISABLE:		"禁用部分循环",
LOOP_SECTION_ENABLE:		"使循环节",
LOOP_MARK_START:			"商标节的开始",
LOOP_MARK_END:				"商标节结束",
PREVIEW_START:				"单击“开始视频预览。",
PREVIEW_END:				"结束视频预览。",
LYRICS_BUTTON_HIDE:			"隐藏歌词",
LYRICS_BUTTON_SHOW:			"显示歌词",
LYRICS_BUTTON_LOAD:			"负载",
LYRICS_BUTTON_TRY:			"尝试手动...",
LYRICS_LYRICS:				"歌词",
LYRICS_LYRICS_FOR:			"歌词为： %song",
LYRICS_TITLE_INFO:			"插入艺术家和歌曲名称来搜索。",
LYRICS_TITLE_INFO_EX:		"连字符分隔（像这样：艺术家 -标题）。",
LYRICS_SEARCH_START:		"搜索 “%song”...",
LYRICS_SEARCH_NO_RESULT:	"没有结果 “%song”.",
LYRICS_SEARCH_FOUND:		"歌词找到。载入中...",
LYRICS_SEARCH_NOT_FOUND:	"歌词都没有发现，没有更多的组合尝试。",
LYRICS_PARSE_SEARCH:		"解析搜索结果...",
LYRICS_PARSE_LYRICS:		"歌词解析数据...",
LYRICS_PARSE_SUCCESS:		"歌词成功解析。",
LYRICS_PARSE_ERROR:			"歌词被发现，但不能被解析。抱歉。",
LYRICS_TITLE_INVALID:		"视频的标题不匹配“艺术家-标题“模式！",
RATING_LIKE:				"%pcent% 人顶了此视频",
RATING_NO_DATA:				"评等资料。"
},
// 广州话 / 廣州話 (Cantonese)
// "zh_HK": {
// },
// 中文 (繁體) (Traditional Chinese)
//	Thanks to:
//		Yang
"zh_TW": {
PREFERENCES:				"偏好設定...",
DOWNLOAD_VIDEO:				"下載影片",
DOWNLOAD_EMPTY:				"(空)",
DOWNLOAD_EMPTY_TIP:			"找不到可下載的資料",
DOWNLOAD_UNKNOWN_TIP:		"未知的影片格式",
STEP_FRAME_FORWARD:			"跳到下一個影格",
SEEK_FORWARD:				"往前跳",
SEEK_BACK:					"往後跳",
POPOUT_PLAYER:				"彈出影片播放器",
LOOP_DISABLE:				"停用重複播放",
LOOP_ENABLE:				"啟用重複播放",
LOOP_SECTION_DISABLE:		"停用選擇範圍重複播放",
LOOP_SECTION_ENABLE:		"啟用選擇範圍重複播放",
LOOP_MARK_START:			"選擇範圍的開始",
LOOP_MARK_END:				"選擇範圍的結束",
PREVIEW_START:				"點選開始影片預覽。",
PREVIEW_END:				"點選結束影片預覽。",
LYRICS_BUTTON_HIDE:			"隱藏歌詞",
LYRICS_BUTTON_SHOW:			"顯示歌詞",
LYRICS_BUTTON_LOAD:			"載入",
LYRICS_BUTTON_TRY:			"手動重試...",
LYRICS_LYRICS:				"歌詞",
LYRICS_LYRICS_FOR:			"歌詞:  %song",
LYRICS_TITLE_INFO:			"輸入歌曲的歌手和標題進行搜尋。",
LYRICS_TITLE_INFO_EX:		"用連字符號分開 (就像:  歌手 - 標題)。",
LYRICS_SEARCH_START:		"搜尋「%song」中...",
LYRICS_SEARCH_NO_RESULT:	"找不到「%song」。",
LYRICS_SEARCH_FOUND:		"已找到歌詞。載入中...",
LYRICS_SEARCH_NOT_FOUND:	"找不到歌詞且已經嘗試過任何可能的選項。",
LYRICS_PARSE_SEARCH:		"分析搜尋結果中...",
LYRICS_PARSE_LYRICS:		"分析歌詞資料中...",
LYRICS_PARSE_SUCCESS:		"已完成歌詞分析。",
LYRICS_PARSE_ERROR:			"已找到歌詞但無法分析。抱歉。",
LYRICS_TITLE_INVALID:		"影片的標題不符合「歌手 - 標題」這樣的格式！",
RATING_LIKE:				"%pcent % 相似",
RATING_NO_DATA:				"無法評價。"
}//,
// isiZulu (Zulu)
// "zu": {
// }
}

});
